import type { Counterpart } from '../../model/domain';
import type { Rng } from '../rng';

const FIRST = [
  [
    'Oliver',
    'Harry',
    'George',
    'Noah',
    'Jack',
    'Theo',
    'Alfie',
    'Oscar',
    'Leo',
    'Charlie',
    'James',
    'Ethan',
    'Thomas',
    'Amir',
    'Isaac',
    'Samuel',
  ],
  [
    'Émile',
    'Mathis',
    'Lucas',
    'Noah',
    'Théo',
    'Adam',
    'Gabriel',
    'Hugo',
    'Jules',
    'Louis',
    'Raphaël',
    'Yanis',
    'Léo',
    'Nathan',
    'Elias',
    'Sacha',
  ],
  [
    'Mateo',
    'Hugo',
    'Martín',
    'Lucas',
    'Pablo',
    'Daniel',
    'Álvaro',
    'Adrián',
    'Diego',
    'Iker',
    'Javier',
    'Manuel',
    'Sergio',
    'Raúl',
    'Álex',
    'Iván',
  ],
  [
    'Jonas',
    'Felix',
    'Leon',
    'Lukas',
    'Finn',
    'Paul',
    'Elias',
    'Niklas',
    'Maximilian',
    'Emil',
    'Anton',
    'Ben',
    'Tobias',
    'Jan',
    'Malik',
    'David',
  ],
  [
    'Lorenzo',
    'Matteo',
    'Leonardo',
    'Alessandro',
    'Francesco',
    'Andrea',
    'Luca',
    'Gabriele',
    'Riccardo',
    'Tommaso',
    'Davide',
    'Marco',
    'Giovanni',
    'Niccolò',
    'Antonio',
    'Federico',
  ],
  [
    'João',
    'Diogo',
    'Tiago',
    'Rodrigo',
    'Gonçalo',
    'Miguel',
    'Tomás',
    'Rafael',
    'Afonso',
    'Duarte',
    'Francisco',
    'André',
    'Pedro',
    'Guilherme',
    'José',
    'Rui',
  ],
] as const;
const LAST = [
  [
    'Smith',
    'Jones',
    'Taylor',
    'Brown',
    'Williams',
    'Wilson',
    'Johnson',
    'Davies',
    'Robinson',
    'Wright',
    'Walker',
    'White',
    'Thompson',
    'Hughes',
    'Edwards',
    'Green',
  ],
  [
    'Moreau',
    'Martin',
    'Lefèvre',
    'Dubois',
    'Bernard',
    'Petit',
    'Durand',
    'Laurent',
    'Robert',
    'Richard',
    'Simon',
    'Michel',
    'Leroy',
    'Roux',
    'Diallo',
    'Lambert',
  ],
  [
    'García',
    'Fernández',
    'González',
    'Rodríguez',
    'López',
    'Martínez',
    'Sánchez',
    'Pérez',
    'Gómez',
    'Ruiz',
    'Moreno',
    'Jiménez',
    'Muñoz',
    'Alonso',
    'Romero',
    'Torres',
  ],
  [
    'Müller',
    'Schmidt',
    'Schneider',
    'Fischer',
    'Weber',
    'Meyer',
    'Wagner',
    'Becker',
    'Hoffmann',
    'Schulz',
    'Koch',
    'Bauer',
    'Richter',
    'Klein',
    'Wolf',
    'Krüger',
  ],
  [
    'Rossi',
    'Russo',
    'Ferrari',
    'Esposito',
    'Bianchi',
    'Romano',
    'Colombo',
    'Ricci',
    'Marino',
    'Greco',
    'Bruno',
    'Gallo',
    'Conti',
    'De Luca',
    'Mancini',
    'Costa',
  ],
  [
    'Silva',
    'Santos',
    'Ferreira',
    'Pereira',
    'Costa',
    'Oliveira',
    'Sousa',
    'Rodrigues',
    'Fernandes',
    'Martins',
    'Almeida',
    'Carvalho',
    'Gomes',
    'Lopes',
    'Marques',
    'Ribeiro',
  ],
] as const;
const ROOTS = [
  [
    'Alder',
    'Ash',
    'Birch',
    'Elm',
    'Oak',
    'Rose',
    'Thorn',
    'Willow',
    'Hart',
    'Brook',
    'Kings',
    'Queens',
    'Crow',
    'Stone',
    'West',
    'East',
    'North',
    'South',
    'Fern',
    'Briar',
    'Red',
    'Green',
    'High',
    'Long',
  ],
  [
    'Val',
    'Mont',
    'Belle',
    'Clair',
    'Font',
    'Roche',
    'Vau',
    'Beau',
    'Port',
    'Saint',
    'Rive',
    'Château',
    'Bois',
    'Pont',
    'Grand',
    'Petit',
    'Haut',
    'Bas',
    'Neu',
    'Viel',
    'Blanc',
    'Vert',
    'Or',
    'Lac',
  ],
  [
    'Val',
    'Monte',
    'Villa',
    'Cala',
    'Río',
    'Costa',
    'Sierra',
    'Vela',
    'Puerto',
    'Castro',
    'Fuente',
    'Torra',
    'Alto',
    'Bajo',
    'San',
    'Santa',
    'Buen',
    'Lago',
    'Prado',
    'Roble',
    'Oliva',
    'Campo',
    'Peña',
    'Arco',
  ],
  [
    'Nord',
    'Süd',
    'West',
    'Ost',
    'Falken',
    'Rosen',
    'Eichen',
    'Linden',
    'Stein',
    'Hohen',
    'Alten',
    'Neu',
    'Buchen',
    'Tannen',
    'Sonnen',
    'Wald',
    'Berg',
    'Tal',
    'Grün',
    'Rot',
    'Blau',
    'Silber',
    'Gold',
    'Kirch',
  ],
  [
    'Bella',
    'Monte',
    'Porta',
    'Vera',
    'Casa',
    'Lago',
    'Terra',
    'Vita',
    'Val',
    'Ponte',
    'Rocca',
    'Castel',
    'Fontana',
    'Prato',
    'Campo',
    'Borgo',
    'Pietra',
    'Marina',
    'Bosco',
    'Sole',
    'Costa',
    'Serra',
    'San',
    'Santa',
  ],
  [
    'Vila',
    'Monte',
    'Vale',
    'Porto',
    'Fonte',
    'Serra',
    'Rio',
    'Lago',
    'Campo',
    'Castelo',
    'Ponte',
    'Costa',
    'Santa',
    'São',
    'Quinta',
    'Ribeira',
    'Pedra',
    'Mar',
    'Mata',
    'Alto',
    'Baixo',
    'Bela',
    'Nova',
    'Estrela',
  ],
] as const;
const ENDINGS = [
  [
    'haven',
    'bridge',
    'wick',
    'field',
    'ford',
    'ton',
    'bury',
    'chester',
    'ham',
    'mouth',
    'worth',
    'stead',
  ],
  [
    'mont',
    'ville',
    'sur-Lac',
    'court',
    'bois',
    'rive',
    'val',
    'bourg',
    'sur-Mer',
    'font',
    'ac',
    'ière',
  ],
  [
    'verde',
    'claro',
    'del Mar',
    'alto',
    'blanco',
    'roja',
    'nuevo',
    'dorado',
    'del Río',
    'largo',
    'bello',
    'sereno',
  ],
  ['hausen', 'berg', 'heim', 'dorf', 'feld', 'burg', 'bach', 'tal', 'au', 'rode', 'brück', 'stadt'],
  [
    'verde',
    'chiara',
    'alta',
    'nuova',
    'bella',
    'marina',
    'del Sole',
    'del Lago',
    'lunga',
    'serena',
    'bianca',
    'dorata',
  ],
  [
    'Clara',
    'Verde',
    'Nova',
    'Marinha',
    'Alta',
    'Bela',
    'Serena',
    'Dourada',
    'do Mar',
    'do Vale',
    'da Serra',
    'Branca',
  ],
] as const;
export function nationalPersonName(rng: Rng, countryIndex: number): string {
  return `${rng.pick(FIRST[countryIndex]!)} ${rng.pick(LAST[countryIndex]!)}`;
}
export function nationalCityName(countryIndex: number, index: number): string {
  const root = ROOTS[countryIndex]![index % ROOTS[countryIndex]!.length]!;
  const ending =
    ENDINGS[countryIndex]![
      Math.floor(index / ROOTS[countryIndex]!.length) % ENDINGS[countryIndex]!.length
    ]!;
  return `${root}${[2, 5].includes(countryIndex) || ending.startsWith('del ') ? ' ' : ''}${ending}`;
}
export function nationalClubName(city: string, country: Counterpart, index: number): string {
  switch (country) {
    case 'England':
      return `${city} ${['United', 'Athletic', 'Rovers', 'City', 'Wanderers', 'Albion', 'Town', 'FC'][index % 8]}`;
    case 'France':
      return `${['AS', 'US', 'Stade', 'Olympique', 'Racing Club', 'FC'][index % 6]} ${city}`;
    case 'Spain':
      return `${['CD', 'UD', 'Atlético', 'Deportivo', 'CF'][index % 5]} ${city}`;
    case 'Germany':
      return `${['FC', 'SV', 'TSV', 'SpVgg', 'VfB'][index % 5]} ${city} ${1890 + (index % 110)}`;
    case 'Italy':
      return `${['AC', 'AS', 'US', 'Calcio', 'Polisportiva'][index % 5]} ${city}`;
    case 'Portugal':
      return `${['FC', 'SC', 'CD', 'GD', 'UD'][index % 5]} ${city}`;
  }
}
export function nationalStadiumName(city: string, countryIndex: number): string {
  return [
    `${city} Park`,
    `Stade de ${city}`,
    `Estadio de ${city}`,
    `${city} Stadion`,
    `Stadio di ${city}`,
    `Estádio de ${city}`,
  ][countryIndex]!;
}
