import type {
  ClubStatus,
  Counterpart,
  DivisionProfile,
  LeagueZone,
  NationalProfile,
  RuleSource,
  Tier,
} from '../../model/domain';

const source = (title: string, url: string, referenceSeason = '2026/27'): RuleSource => ({
  title,
  url,
  referenceSeason,
});
const SOURCES: Record<Counterpart, RuleSource[]> = {
  England: [
    source(
      'EFL Championship playoff reform',
      'https://www.efl.com/news/2026/march/05/efl-statement--sky-bet-championship-play-off-format/',
    ),
    source(
      'EFL regulations',
      'https://images.gc.eflservices.co.uk/c99e4490-a070-11f1-b53b-9be1de328ad3.pdf',
    ),
    source(
      'EFL promotion playoff rules',
      'https://images.gc.eflservices.co.uk/659e3bb0-7b8d-11f1-b366-6527b2d4899f.pdf',
    ),
    source(
      'National League playoff appendix B (carryover)',
      'https://images.gc.nationalleagueservices.co.uk/f1dfd150-97b4-11f0-b55f-398469255719.pdf',
      '2025/26',
    ),
    source(
      'National League regional playoff appendix C (carryover)',
      'https://images.gc.nationalleagueservices.co.uk/f173c910-97b4-11f0-8211-c57fd24070cf.pdf',
      '2025/26',
    ),
    source(
      'FA National League System allocations',
      'https://www.thefa.com/news/2026/may/14/nls-club-allocations-2026-27',
    ),
  ],
  France: [
    source(
      'FFF professional Ligue 3 reform',
      'https://www.fff.fr/article/16778-la-fff-officialise-la-ligue-3-professionnelle.html',
    ),
    source(
      'FFF adopted competition regulations',
      'https://media.fff.fr/uploads/documents/textes-votes-a-l-ag-fff-du-06.06.2026.pdf',
    ),
    source(
      'LFP sporting regulations',
      'https://www.lfp.fr/assets/25_26_Reglement_Competitions_29_07_2024_5055b664e4.pdf',
      '2025/26',
    ),
  ],
  Spain: [
    source(
      'RFEF Primera and Segunda División',
      'https://rfef.es/sites/default/files/pdf/circulares/1._Circular_84_-_CNL_Primera_y_Segunda_Division___Anexo.pdf',
    ),
    source(
      'RFEF Primera Federación',
      'https://rfef.es/sites/default/files/pdf/circulares/2._Circular_85_-_CNL_Primera_Federacion___Anexo.pdf',
    ),
    source(
      'RFEF Segunda Federación',
      'https://rfef.es/sites/default/files/pdf/circulares/3._Circular_86_-_CNL_Segunda_Federacion___Anexo.pdf',
    ),
  ],
  Germany: [
    source(
      'Regionalliga West movement rules',
      'https://wdfv.de/download/herren-regionalliga-west/herren-regionalliga-west-auf-und-abstiegsregelung-fuer-die-saison-20262027.pdf',
    ),
    source(
      'Regionalliga North rules',
      'https://www.nordfv.de/der-nfv/satzung-ordnungen/spielordnung',
    ),
    source(
      'Regionalliga Northeast movement rules',
      'https://www.nofv-online.de/files/Inhalt/Aktuelles/2026_Q2/260626_Herren_Auf-und%20Abstiegsregelung%202026-27_final.pdf',
    ),
    source(
      'Regionalliga Southwest rules',
      'https://res.cloudinary.com/rlsw/image/upload/v1785911302/Spielordnung_RLSW_Stand_Stand_01.08.26_pxvhrg.pdf',
    ),
    source(
      'Regionalliga Bavaria movement rules',
      'https://www.bfv.de/binaries/content/assets/inhalt/der-bfv/satzung-richtlinien-amtliches/amtliches/spielausschuss/auf--und-abstiegsregelung-regionalliga-bayern-2026_2027.pdf',
    ),
    source(
      'Bundesliga promotion and relegation',
      'https://www.bundesliga.com/en/faq/what-are-the-rules-and-regulations-of-soccer/how-does-promotion-and-relegation-work-in-the-bundesliga-10645',
    ),
    source(
      'DFB regional promotion rotation',
      'https://www.dfb.de/news/detail/aufstieg-von-regionalliga-zur-3-liga-fragen-und-antworten-208044',
    ),
    source(
      'Bavarian regional regulations',
      'https://www.bfv.de/spielbetrieb-verbandsleben/ligabetrieb/regionalliga-bayern',
    ),
  ],
  Italy: [
    source(
      'Serie D group allocation',
      'https://lnd.it/seried/attivita-interregionale/i-gironi-del-campionato-2026-2027/',
    ),
    source(
      'Serie D survival rules',
      'https://lnd.it/seried/il-regolamento-playout-per-la-stagione-2026-2027/',
    ),
    source(
      'Serie B promotion and survival regulations',
      'https://d5rzfs5ck83rq.cloudfront.net/legab.it/img/news/2025-26/39-deroga-art-51-noif-classifica-finale-play-off-e-play-out-campionato-serie-b-ss-2025-2026.pdf',
      '2025/26',
    ),
    source('Serie C official competition documents', 'https://www.seriec.com/documentazione'),
    source(
      'Serie A title and survival deciders (carryover)',
      'https://www.figc.it/media/274515/331-deroga-art-51-noif-determinazione-classifica-campionato-serie-a-ss-2025-2026.pdf',
      '2025/26',
    ),
    source(
      'FIGC NOIF classification and reserve regulations',
      'https://files.figc.it/view/acePublic/alias/contentid/1qzg5l96u12qfpnd689/0/tit3_noif_art_da47a70_------------aggiornato-al_CU209A_del_06-05-2026.pdf',
    ),
  ],
  Portugal: [
    source(
      'Liga Portugal regulations',
      'https://www.ligaportugal.pt/backoffice/assets/20260701_RC_2026_27_f53785bcd4.pdf',
    ),
    source('FPF Liga 3 format', 'https://www.fpf.pt/DownloadDocument.ashx?id=32598'),
    source(
      'FPF Campeonato de Portugal format',
      'https://www.fpf.pt/DownloadDocument.ashx?id=32599',
    ),
  ],
};

function division(
  country: Counterpart,
  tier: Tier,
  name: string,
  sizes: number[],
  regions: string[],
  promotion: number,
  relegation: number,
  rules: string,
  playoffRanks: [number, number] | null = null,
  survivalRanks: [number, number] | null = null,
  status: ClubStatus = 'professional',
): DivisionProfile {
  const zones: LeagueZone[] = [];
  if (promotion)
    zones.push({ from: 1, to: promotion, kind: 'promotion', label: 'Automatic promotion' });
  if (playoffRanks)
    zones.push({
      from: playoffRanks[0],
      to: playoffRanks[1],
      kind: 'promotion-playoff',
      label: 'Promotion playoff',
    });
  if (relegation)
    zones.push({
      from: sizes[0]! - relegation + 1,
      to: sizes[0]!,
      kind: 'relegation',
      label: 'Automatic relegation',
    });
  if (survivalRanks)
    zones.push({
      from: survivalRanks[0],
      to: survivalRanks[1],
      kind: 'survival-playoff',
      label: 'Survival playoff',
    });
  return {
    id: `${country.toLowerCase()}:${tier}`,
    name,
    tier,
    groups: sizes.map((size, index) => ({
      id: `${tier}:${index}`,
      name: regions[index] ?? `Group ${String.fromCharCode(65 + index)}`,
      region: regions[index] ?? `Region ${index + 1}`,
      size,
    })),
    status,
    regularRounds: Math.max(...sizes.map((size) => 2 * (size % 2 ? size : size - 1))),
    automaticPromotion: promotion,
    automaticRelegation: relegation,
    zones,
    rules,
    sources: SOURCES[country],
  };
}
const d = division;
export function germanRegionalZones(region: string, season: number): LeagueZone[] {
  const rotating = ['Northeast', 'Bavaria', 'North'][(((season - 2026) % 3) + 3) % 3];
  const direct = region === 'West' || region === 'Southwest' || region === rotating;
  return [
    {
      from: 1,
      to: 1,
      kind: direct ? 'promotion' : 'promotion-playoff',
      label: direct ? 'Automatic promotion' : 'Regional promotion playoff',
    },
  ];
}
export const NATIONAL_PROFILES: NationalProfile[] = [
  {
    id: 'england-2026-27-v1',
    version: 1,
    counterpart: 'England',
    referenceSeason: '2026/27',
    sources: SOURCES.England,
    adaptations: [
      'Fictional club identities and geography; sporting reference rules remain frozen.',
      'National League playoff appendices retain the published 2025/26 bracket as an explicitly sourced carryover.',
    ],
    divisions: [
      d('England', 1, 'Premier League', [20], ['National'], 0, 3, 'Bottom three relegated.'),
      d(
        'England',
        2,
        'Championship',
        [24],
        ['National'],
        2,
        3,
        'Top two promoted; third through eighth contest promotion playoffs.',
        [3, 8],
      ),
      d(
        'England',
        3,
        'League One',
        [24],
        ['National'],
        2,
        4,
        'Top two promoted; third through sixth contest two-leg semifinals and a neutral final.',
        [3, 6],
      ),
      d(
        'England',
        4,
        'League Two',
        [24],
        ['National'],
        3,
        2,
        'Top three promoted; fourth through seventh contest two-leg semifinals and a neutral final.',
        [4, 7],
      ),
      d(
        'England',
        5,
        'National League',
        [24],
        ['National'],
        1,
        4,
        'Champion promoted; second through seventh contest seeded single-match playoffs.',
        [2, 7],
      ),
      d(
        'England',
        6,
        'National League',
        [24, 24],
        ['North', 'South'],
        1,
        4,
        'Each regional champion promoted; second through seventh contest seeded playoffs for one further place per group.',
        [2, 7],
        null,
        'semi-professional',
      ),
    ],
  },
  {
    id: 'france-2026-27-v1',
    version: 1,
    counterpart: 'France',
    referenceSeason: '2026/27',
    sources: SOURCES.France,
    adaptations: [
      'No administrative withdrawals or reprieves; the exceptional 17-club 2025/26 National is not modeled.',
    ],
    divisions: [
      d(
        'France',
        1,
        'Ligue 1',
        [18],
        ['National'],
        0,
        2,
        'Bottom two relegated; sixteenth enters a two-leg survival barrage.',
        null,
        [16, 16],
      ),
      d(
        'France',
        2,
        'Ligue 2',
        [18],
        ['National'],
        2,
        2,
        'Fifth visits fourth; winner visits third; winner faces Ligue 1 sixteenth. Sixteenth faces the Ligue 3 playoff winner.',
        [3, 5],
        [16, 16],
      ),
      d(
        'France',
        3,
        'Ligue 3',
        [18],
        ['National'],
        2,
        3,
        'Third versus sixth and fourth versus fifth; single-match final then two-leg barrage against Ligue 2 sixteenth.',
        [3, 6],
      ),
      d(
        'France',
        4,
        'National 1',
        [16, 16, 16],
        ['Northwest', 'Northeast', 'South'],
        1,
        2,
        'Best eligible club in each group promoted. Bottom two per group and worst two fourteenth-placed clubs relegated.',
        null,
        [14, 14],
        'semi-professional',
      ),
    ],
  },
  {
    id: 'spain-2026-27-v1',
    version: 1,
    counterpart: 'Spain',
    referenceSeason: '2026/27',
    sources: SOURCES.Spain,
    adaptations: ['Fictional regional allocation replaces the real annual geographic club draw.'],
    divisions: [
      d('Spain', 1, 'Primera División', [20], ['National'], 0, 3, 'Bottom three relegated.'),
      d(
        'Spain',
        2,
        'Segunda División',
        [22],
        ['National'],
        2,
        4,
        'Third through sixth contest two rounds over two legs; aggregate ties favor the higher-ranked club after extra time.',
        [3, 6],
      ),
      d(
        'Spain',
        3,
        'Primera Federación',
        [20, 20],
        ['North', 'South'],
        1,
        5,
        'Group champions promoted; second through fifth contest cross-group playoffs for two additional places.',
        [2, 5],
      ),
      d(
        'Spain',
        4,
        'Segunda Federación',
        [18, 18, 18, 18, 18],
        ['Northwest', 'Northeast', 'Central', 'East', 'South'],
        1,
        5,
        'Group champions promoted; second through fifth contest two cross-group playoff rounds for five additional places. Worst four thirteenth-placed clubs contest survival ties.',
        [2, 5],
        [13, 13],
        'semi-professional',
      ),
    ],
  },
  {
    id: 'germany-2026-27-v1',
    version: 1,
    counterpart: 'Germany',
    referenceSeason: '2026/27',
    sources: SOURCES.Germany,
    adaptations: [
      'Regional membership uses fictional fixed geography; conditional regional capacity rules depend on incoming relegated clubs.',
      'Northeast incoming counts above the published zero/one-club cases use capacity balancing; West may expand after its four ordinary relegations.',
    ],
    divisions: [
      d(
        'Germany',
        1,
        'Bundesliga',
        [18],
        ['National'],
        0,
        2,
        'Bottom two relegated; sixteenth faces second-tier third over two legs.',
        null,
        [16, 16],
      ),
      d(
        'Germany',
        2,
        '2. Bundesliga',
        [18],
        ['National'],
        2,
        2,
        'Top two promoted; third enters promotion tie. Sixteenth faces third-tier third.',
        [3, 3],
        [16, 16],
      ),
      d(
        'Germany',
        3,
        '3. Liga',
        [20],
        ['National'],
        2,
        4,
        'Top two eligible clubs promoted; next eligible club enters promotion tie.',
        [3, 3],
      ),
      d(
        'Germany',
        4,
        'Regionalliga',
        [18, 18, 18, 18, 19],
        ['North', 'Northeast', 'West', 'Southwest', 'Bavaria'],
        0,
        0,
        'West and Southwest champions promoted; Northeast champion receives the 2026/27 direct place; North and Bavaria champions contest a two-leg playoff. Bavaria has nineteen clubs and a bye.',
        [1, 1],
        null,
        'semi-professional',
      ),
    ],
  },
  {
    id: 'italy-2026-27-v1',
    version: 1,
    counterpart: 'Italy',
    referenceSeason: '2026/27',
    sources: SOURCES.Italy,
    adaptations: [
      'Serie B conditional thresholds explicitly refer to the published 2025/26 regulation.',
      'Serie A title and survival deciders retain the published 2025/26 rule; they are not presented as verified 2026/27 reforms.',
    ],
    divisions: [
      d(
        'Italy',
        1,
        'Serie A',
        [20],
        ['National'],
        0,
        3,
        'Bottom three relegated; decisive equal-point places can require a deciding match.',
      ),
      d(
        'Italy',
        2,
        'Serie B',
        [20],
        ['National'],
        2,
        3,
        'Third promoted directly only with a lead over fourth exceeding fourteen points; otherwise third through eighth contest playoffs. Sixteenth versus seventeenth survival tie unless their gap exceeds four points.',
        [3, 8],
        [16, 17],
      ),
      d(
        'Italy',
        3,
        'Serie C',
        [20, 20, 20],
        ['Northwest', 'Northeast', 'South'],
        1,
        1,
        'Three champions and one national playoff winner promoted. National playoffs include the Serie C cup qualification place and seeded group stages. Survival ties determine remaining relegations.',
        [2, 10],
        [16, 19],
      ),
      d(
        'Italy',
        4,
        'Serie D',
        Array<number>(9).fill(18),
        [
          'Northwest',
          'West',
          'Northeast',
          'North-central',
          'Central-west',
          'Central-east',
          'Southwest',
          'Southeast',
          'Islands',
        ],
        1,
        2,
        'Nine champions promoted. Second through fifth contest ranking playoffs without automatic promotion. Thirteenth versus sixteenth and fourteenth versus fifteenth survival ties, subject to point-gap rules.',
        [2, 5],
        [13, 16],
        'semi-professional',
      ),
    ],
  },
  {
    id: 'portugal-2026-27-v1',
    version: 1,
    counterpart: 'Portugal',
    referenceSeason: '2026/27',
    sources: SOURCES.Portugal,
    adaptations: [
      'Fictional club identities; two-stage competitions retain separate phase tables.',
      'Exactly ten Liga 3 first-phase points receives the rank bonus only under the general bonus table; the explanatory footnotes omit exactly ten.',
    ],
    divisions: [
      d(
        'Portugal',
        1,
        'Primeira Liga',
        [18],
        ['National'],
        0,
        2,
        'Bottom two relegated; sixteenth faces the highest eligible second-tier club below automatic promotion places.',
        null,
        [16, 16],
      ),
      d(
        'Portugal',
        2,
        'Liga Portugal 2',
        [18],
        ['National'],
        2,
        2,
        'Top two eligible clubs promoted; next eligible enters two-leg barrage. Sixteenth faces Liga 3 promotion-phase third.',
        [3, 3],
        [16, 16],
      ),
      d(
        'Portugal',
        3,
        'Liga 3',
        [10, 10],
        ['North', 'South'],
        0,
        0,
        'Top four per initial group enter an eight-club promotion league; top two promoted and third enters barrage. Remaining clubs enter two six-club survival groups with bonus points; bottom two per group relegated.',
        [1, 4],
      ),
      d(
        'Portugal',
        4,
        'Campeonato de Portugal',
        [14, 14, 14, 14],
        ['North', 'North-central', 'South-central', 'South'],
        0,
        2,
        'Top two per group enter two promotion groups of four; top two per promotion group promoted; group winners contest championship final. Eleventh and twelfth enter two-leg survival ties.',
        [1, 2],
        [11, 12],
        'semi-professional',
      ),
    ],
  },
];
