import type { CountryIdentity } from './types';

/**
 * England: Premier League, Championship, League One and League Two memberships for 2026/27
 * (after the 2025/26 promotions, relegations and playoffs, with York City and Rochdale up from
 * the National League). The National League and National League North/South are filled with
 * generated clubs in real towns.
 */
export const ENGLAND: CountryIdentity = {
  counterpart: 'England',
  name: 'England',
  adjective: 'English',
  divisions: {
    1: { name: 'English Premier Division', reference: 'Premier League' },
    2: { name: 'English Championship', reference: 'EFL Championship' },
    3: { name: 'English Division One', reference: 'EFL League One' },
    4: { name: 'English Division Two', reference: 'EFL League Two' },
    5: { name: 'English National Division', reference: 'National League' },
    6: {
      name: 'English National Division',
      reference: 'National League North/South',
      groups: ['North', 'South'],
    },
  },
  cup: { name: 'English Association Cup', reference: 'FA Cup' },
  clubs: {
    1: [
      {
        name: 'North London Cannons',
        reference: 'Arsenal',
        city: 'London',
        lat: 51.555,
        lon: -0.108,
        region: 'South',
        colours: ['#ef0107', '#ffffff', '#063672'],
        pattern: 'solid',
        stadium: 'Holloway Arena',
        capacity: 60704,
        stature: 10,
      },
      {
        name: 'Aston Claret Lions',
        reference: 'Aston Villa',
        city: 'Birmingham',
        lat: 52.509,
        lon: -1.885,
        region: 'North',
        colours: ['#670e36', '#95bfe5', '#fee505'],
        pattern: 'solid',
        stadium: 'Witton Lane Park',
        capacity: 42640,
        stature: 8,
      },
      {
        name: 'Bournemouth Cherries',
        reference: 'AFC Bournemouth',
        city: 'Bournemouth',
        lat: 50.735,
        lon: -1.838,
        region: 'South',
        colours: ['#da291c', '#000000', '#ffffff'],
        pattern: 'stripes',
        stadium: 'Kings Park Ground',
        capacity: 11307,
        stature: 6,
      },
      {
        name: 'Brentford Bees',
        reference: 'Brentford',
        city: 'London',
        lat: 51.491,
        lon: -0.289,
        region: 'South',
        colours: ['#e30613', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Lionel Road Stadium',
        capacity: 17250,
        stature: 5,
      },
      {
        name: 'Brighton Seagulls',
        reference: 'Brighton & Hove Albion',
        city: 'Brighton',
        lat: 50.862,
        lon: -0.083,
        region: 'South',
        colours: ['#0057b8', '#ffffff', '#ffcd00'],
        pattern: 'stripes',
        stadium: 'Falmer Downs Stadium',
        capacity: 31876,
        stature: 7,
      },
      {
        name: 'West London Blues',
        reference: 'Chelsea',
        city: 'London',
        lat: 51.482,
        lon: -0.191,
        region: 'South',
        colours: ['#034694', '#ffffff', '#dba111'],
        pattern: 'solid',
        stadium: 'Fulham Road Stadium',
        capacity: 40173,
        stature: 9,
      },
      {
        name: 'Coventry Sky Blues',
        reference: 'Coventry City',
        city: 'Coventry',
        lat: 52.448,
        lon: -1.496,
        region: 'North',
        colours: ['#76b5e8', '#ffffff', '#1d2d5c'],
        pattern: 'solid',
        stadium: 'Rowleys Green Arena',
        capacity: 32609,
        stature: 4,
      },
      {
        name: 'South London Eagles',
        reference: 'Crystal Palace',
        city: 'London',
        lat: 51.398,
        lon: -0.086,
        region: 'South',
        colours: ['#1b458f', '#c4122e', '#ffffff'],
        pattern: 'stripes',
        stadium: 'Holmesdale Road Ground',
        capacity: 25486,
        stature: 6,
      },
      {
        name: 'Merseyside Toffees',
        reference: 'Everton',
        city: 'Liverpool',
        lat: 53.426,
        lon: -3.0,
        region: 'North',
        colours: ['#003399', '#ffffff', '#1d1d1b'],
        pattern: 'solid',
        stadium: 'Waterfront Dock Stadium',
        capacity: 52888,
        stature: 7,
      },
      {
        name: 'Fulham Cottagers',
        reference: 'Fulham',
        city: 'London',
        lat: 51.475,
        lon: -0.222,
        region: 'South',
        colours: ['#ffffff', '#000000', '#cc0000'],
        pattern: 'solid',
        stadium: 'Riverside Cottage Ground',
        capacity: 29600,
        stature: 5,
      },
      {
        name: 'Hull Tigers',
        reference: 'Hull City',
        city: 'Hull',
        lat: 53.746,
        lon: -0.368,
        region: 'North',
        colours: ['#f5a12d', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Walton Street Stadium',
        capacity: 25586,
        stature: 3,
      },
      {
        name: 'Ipswich Tractor Boys',
        reference: 'Ipswich Town',
        city: 'Ipswich',
        lat: 52.055,
        lon: 1.145,
        region: 'South',
        colours: ['#0033a0', '#ffffff', '#de2c37'],
        pattern: 'solid',
        stadium: 'Constantine Road Ground',
        capacity: 29673,
        stature: 3,
      },
      {
        name: 'Leeds Peacocks',
        reference: 'Leeds United',
        city: 'Leeds',
        lat: 53.778,
        lon: -1.572,
        region: 'North',
        colours: ['#ffffff', '#1d428a', '#ffcd00'],
        pattern: 'solid',
        stadium: 'Beeston Road Stadium',
        capacity: 37645,
        stature: 6,
      },
      {
        name: 'Merseyside Reds',
        reference: 'Liverpool',
        city: 'Liverpool',
        lat: 53.431,
        lon: -2.961,
        region: 'North',
        colours: ['#c8102e', '#ffffff', '#00b2a9'],
        pattern: 'solid',
        stadium: 'Walton Breck Ground',
        capacity: 61276,
        stature: 10,
      },
      {
        name: 'Manchester Sky Blues',
        reference: 'Manchester City',
        city: 'Manchester',
        lat: 53.483,
        lon: -2.2,
        region: 'North',
        colours: ['#6cabdd', '#ffffff', '#1c2c5b'],
        pattern: 'solid',
        stadium: 'Eastlands Stadium',
        capacity: 61470,
        stature: 10,
      },
      {
        name: 'Manchester Reds',
        reference: 'Manchester United',
        city: 'Manchester',
        lat: 53.463,
        lon: -2.291,
        region: 'North',
        colours: ['#da291c', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Trafford Wharf Stadium',
        capacity: 74197,
        stature: 10,
      },
      {
        name: 'Tyneside Magpies',
        reference: 'Newcastle United',
        city: 'Newcastle upon Tyne',
        lat: 54.976,
        lon: -1.622,
        region: 'North',
        colours: ['#241f20', '#ffffff', '#41b6e6'],
        pattern: 'stripes',
        stadium: 'Gallowgate Park',
        capacity: 52305,
        stature: 8,
      },
      {
        name: 'Nottingham Tricky Trees',
        reference: 'Nottingham Forest',
        city: 'Nottingham',
        lat: 52.94,
        lon: -1.133,
        region: 'North',
        colours: ['#dd0000', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Trentside Ground',
        capacity: 30404,
        stature: 6,
      },
      {
        name: 'Wearside Black Cats',
        reference: 'Sunderland',
        city: 'Sunderland',
        lat: 54.915,
        lon: -1.388,
        region: 'North',
        colours: ['#eb172b', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Monkwearmouth Stadium',
        capacity: 49000,
        stature: 6,
      },
      {
        name: 'North London Lilywhites',
        reference: 'Tottenham Hotspur',
        city: 'London',
        lat: 51.604,
        lon: -0.066,
        region: 'South',
        colours: ['#ffffff', '#132257', '#c6a764'],
        pattern: 'solid',
        stadium: 'High Road Stadium',
        capacity: 62850,
        stature: 9,
      },
    ],
    2: [
      {
        name: 'Birmingham Blues',
        reference: 'Birmingham City',
        city: 'Birmingham',
        lat: 52.476,
        lon: -1.868,
        region: 'North',
        colours: ['#0000ff', '#ffffff', '#e30613'],
        pattern: 'solid',
        stadium: 'Bordesley Green Ground',
        capacity: 29409,
        stature: 7,
      },
      {
        name: 'Blackburn Riversiders',
        reference: 'Blackburn Rovers',
        city: 'Blackburn',
        lat: 53.729,
        lon: -2.489,
        region: 'North',
        colours: ['#009ee0', '#ffffff', '#e30613'],
        pattern: 'halves',
        stadium: 'Darwen Riverside Ground',
        capacity: 31367,
        stature: 6,
      },
      {
        name: 'Bolton Trotters',
        reference: 'Bolton Wanderers',
        city: 'Bolton',
        lat: 53.581,
        lon: -2.536,
        region: 'North',
        colours: ['#ffffff', '#263c7e', '#e30613'],
        pattern: 'solid',
        stadium: 'Middlebrook Stadium',
        capacity: 28723,
        stature: 5,
      },
      {
        name: 'Bristol Robins',
        reference: 'Bristol City',
        city: 'Bristol',
        lat: 51.44,
        lon: -2.62,
        region: 'South',
        colours: ['#e21a23', '#ffffff', '#1d1d1b'],
        pattern: 'solid',
        stadium: 'Ashton Vale Stadium',
        capacity: 27000,
        stature: 6,
      },
      {
        name: 'Burnley Clarets',
        reference: 'Burnley',
        city: 'Burnley',
        lat: 53.789,
        lon: -2.23,
        region: 'North',
        colours: ['#6c1d45', '#99d6ea', '#ffffff'],
        pattern: 'solid',
        stadium: 'Harry Potts Way Ground',
        capacity: 21944,
        stature: 7,
      },
      {
        name: 'Cardiff Bluebirds',
        reference: 'Cardiff City',
        city: 'Cardiff',
        lat: 51.473,
        lon: -3.203,
        region: 'South',
        colours: ['#0070b5', '#ffffff', '#e30613'],
        pattern: 'solid',
        stadium: 'Leckwith Stadium',
        capacity: 33280,
        stature: 6,
      },
      {
        name: 'Greenwich Addicks',
        reference: 'Charlton Athletic',
        city: 'London',
        lat: 51.486,
        lon: 0.036,
        region: 'South',
        colours: ['#d4021d', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Floyd Road Ground',
        capacity: 27111,
        stature: 4,
      },
      {
        name: 'Derby Rams',
        reference: 'Derby County',
        city: 'Derby',
        lat: 52.915,
        lon: -1.447,
        region: 'North',
        colours: ['#ffffff', '#000000', '#a89968'],
        pattern: 'solid',
        stadium: 'Derwent Riverside Stadium',
        capacity: 32956,
        stature: 6,
      },
      {
        name: 'Lincoln Imps',
        reference: 'Lincoln City',
        city: 'Lincoln',
        lat: 53.218,
        lon: -0.541,
        region: 'North',
        colours: ['#e30613', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Witham Valley Ground',
        capacity: 10669,
        stature: 2,
      },
      {
        name: 'Teesside Ironsides',
        reference: 'Middlesbrough',
        city: 'Middlesbrough',
        lat: 54.578,
        lon: -1.217,
        region: 'North',
        colours: ['#e11b22', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Middlehaven Stadium',
        capacity: 34742,
        stature: 7,
      },
      {
        name: 'Bermondsey Lions',
        reference: 'Millwall',
        city: 'London',
        lat: 51.486,
        lon: -0.051,
        region: 'South',
        colours: ['#001d5e', '#ffffff', '#9bb3d8'],
        pattern: 'solid',
        stadium: 'Zampa Road Ground',
        capacity: 20146,
        stature: 5,
      },
      {
        name: 'Norwich Canaries',
        reference: 'Norwich City',
        city: 'Norwich',
        lat: 52.622,
        lon: 1.309,
        region: 'South',
        colours: ['#fff200', '#00a650', '#ffffff'],
        pattern: 'solid',
        stadium: 'Wensum Riverside Ground',
        capacity: 27150,
        stature: 7,
      },
      {
        name: 'Portsmouth Pompey',
        reference: 'Portsmouth',
        city: 'Portsmouth',
        lat: 50.796,
        lon: -1.064,
        region: 'South',
        colours: ['#001489', '#ffffff', '#e30613'],
        pattern: 'solid',
        stadium: 'Frogmore Road Ground',
        capacity: 20867,
        stature: 5,
      },
      {
        name: 'Preston Invincibles',
        reference: 'Preston North End',
        city: 'Preston',
        lat: 53.772,
        lon: -2.688,
        region: 'North',
        colours: ['#ffffff', '#001b44', '#c5a46d'],
        pattern: 'solid',
        stadium: 'Sir Tom Finney Way Ground',
        capacity: 23404,
        stature: 5,
      },
      {
        name: 'Shepherds Bush Hoops',
        reference: 'Queens Park Rangers',
        city: 'London',
        lat: 51.509,
        lon: -0.232,
        region: 'South',
        colours: ['#1d5ba4', '#ffffff', '#e30613'],
        pattern: 'hoops',
        stadium: 'South Africa Road Ground',
        capacity: 18439,
        stature: 5,
      },
      {
        name: 'Sheffield Blades',
        reference: 'Sheffield United',
        city: 'Sheffield',
        lat: 53.37,
        lon: -1.471,
        region: 'North',
        colours: ['#ee2737', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Cherry Street Ground',
        capacity: 32050,
        stature: 7,
      },
      {
        name: 'Southampton Saints',
        reference: 'Southampton',
        city: 'Southampton',
        lat: 50.906,
        lon: -1.391,
        region: 'South',
        colours: ['#d71920', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Northam Stadium',
        capacity: 32384,
        stature: 8,
      },
      {
        name: 'Stoke Potters',
        reference: 'Stoke City',
        city: 'Stoke-on-Trent',
        lat: 52.988,
        lon: -2.175,
        region: 'North',
        colours: ['#e03a3e', '#ffffff', '#1b449c'],
        pattern: 'stripes',
        stadium: 'Trentham Lakes Stadium',
        capacity: 30089,
        stature: 6,
      },
      {
        name: 'Swansea Jacks',
        reference: 'Swansea City',
        city: 'Swansea',
        lat: 51.643,
        lon: -3.935,
        region: 'South',
        colours: ['#ffffff', '#121212', '#e1b33a'],
        pattern: 'solid',
        stadium: 'Landore Stadium',
        capacity: 21088,
        stature: 5,
      },
      {
        name: 'Watford Hornets',
        reference: 'Watford',
        city: 'Watford',
        lat: 51.65,
        lon: -0.401,
        region: 'South',
        colours: ['#fbee23', '#ed2127', '#000000'],
        pattern: 'solid',
        stadium: 'Occupation Road Ground',
        capacity: 22200,
        stature: 6,
      },
      {
        name: 'West Bromwich Throstles',
        reference: 'West Bromwich Albion',
        city: 'West Bromwich',
        lat: 52.509,
        lon: -1.964,
        region: 'North',
        colours: ['#122f67', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Halfords Lane Ground',
        capacity: 26688,
        stature: 7,
      },
      {
        name: 'East London Hammers',
        reference: 'West Ham United',
        city: 'London',
        lat: 51.539,
        lon: -0.017,
        region: 'South',
        colours: ['#7a263a', '#1bb1e7', '#f3d459'],
        pattern: 'solid',
        stadium: 'Stratford Park Stadium',
        capacity: 62500,
        stature: 9,
      },
      {
        name: 'Black Country Wolves',
        reference: 'Wolverhampton Wanderers',
        city: 'Wolverhampton',
        lat: 52.59,
        lon: -2.13,
        region: 'North',
        colours: ['#fdb913', '#231f20', '#ffffff'],
        pattern: 'solid',
        stadium: 'Waterloo Road Stadium',
        capacity: 31750,
        stature: 9,
      },
      {
        name: 'Wrexham Red Dragons',
        reference: 'Wrexham',
        city: 'Wrexham',
        lat: 53.052,
        lon: -3.004,
        region: 'North',
        colours: ['#d71920', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Mold Road Ground',
        capacity: 12600,
        stature: 5,
      },
    ],
    3: [
      {
        name: 'Wimbledon Dons',
        reference: 'AFC Wimbledon',
        city: 'London',
        lat: 51.431,
        lon: -0.191,
        region: 'South',
        colours: ['#0055a5', '#ffe600', '#ffffff'],
        pattern: 'solid',
        stadium: 'Wandle Valley Ground',
        capacity: 9215,
        stature: 3,
      },
      {
        name: 'Barnsley Tykes',
        reference: 'Barnsley',
        city: 'Barnsley',
        lat: 53.552,
        lon: -1.468,
        region: 'North',
        colours: ['#d71920', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Grove Street Ground',
        capacity: 23287,
        stature: 6,
      },
      {
        name: 'Blackpool Tangerines',
        reference: 'Blackpool',
        city: 'Blackpool',
        lat: 53.805,
        lon: -3.048,
        region: 'North',
        colours: ['#f68712', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Tower View Ground',
        capacity: 16616,
        stature: 5,
      },
      {
        name: 'Bradford Bantams',
        reference: 'Bradford City',
        city: 'Bradford',
        lat: 53.804,
        lon: -1.759,
        region: 'North',
        colours: ['#7a0f2f', '#f9a01b', '#ffffff'],
        pattern: 'stripes',
        stadium: 'Manningham Ground',
        capacity: 25136,
        stature: 6,
      },
      {
        name: 'Bromley Ravens',
        reference: 'Bromley',
        city: 'London',
        lat: 51.39,
        lon: 0.019,
        region: 'South',
        colours: ['#ffffff', '#000000', '#c8a24a'],
        pattern: 'solid',
        stadium: 'Hayes Common Ground',
        capacity: 5000,
        stature: 1,
      },
      {
        name: 'Burton Brewers',
        reference: 'Burton Albion',
        city: 'Burton upon Trent',
        lat: 52.822,
        lon: -1.627,
        region: 'North',
        colours: ['#fdd900', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Princess Way Ground',
        capacity: 6912,
        stature: 3,
      },
      {
        name: 'Cambridge Ambers',
        reference: 'Cambridge United',
        city: 'Cambridge',
        lat: 52.212,
        lon: 0.154,
        region: 'South',
        colours: ['#fdb913', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Newmarket Road Ground',
        capacity: 8127,
        stature: 3,
      },
      {
        name: 'Doncaster Vikings',
        reference: 'Doncaster Rovers',
        city: 'Doncaster',
        lat: 53.51,
        lon: -1.114,
        region: 'North',
        colours: ['#e21e26', '#ffffff', '#000000'],
        pattern: 'hoops',
        stadium: 'Lakeside Stadium',
        capacity: 15231,
        stature: 4,
      },
      {
        name: 'Huddersfield Terriers',
        reference: 'Huddersfield Town',
        city: 'Huddersfield',
        lat: 53.654,
        lon: -1.768,
        region: 'North',
        colours: ['#0e63ad', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Colne Riverside Stadium',
        capacity: 24121,
        stature: 6,
      },
      {
        name: 'Leicester Foxes',
        reference: 'Leicester City',
        city: 'Leicester',
        lat: 52.62,
        lon: -1.142,
        region: 'North',
        colours: ['#003090', '#fdbe11', '#ffffff'],
        pattern: 'solid',
        stadium: 'Filbert Way Stadium',
        capacity: 32259,
        stature: 9,
      },
      {
        name: 'Leyton Wyverns',
        reference: 'Leyton Orient',
        city: 'London',
        lat: 51.56,
        lon: -0.012,
        region: 'South',
        colours: ['#e2001a', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Oliver Road Ground',
        capacity: 9271,
        stature: 4,
      },
      {
        name: 'Luton Hatters',
        reference: 'Luton Town',
        city: 'Luton',
        lat: 51.884,
        lon: -0.432,
        region: 'South',
        colours: ['#f78f1e', '#002d62', '#ffffff'],
        pattern: 'solid',
        stadium: 'Bury Park Ground',
        capacity: 12000,
        stature: 6,
      },
      {
        name: 'Mansfield Stags',
        reference: 'Mansfield Town',
        city: 'Mansfield',
        lat: 53.138,
        lon: -1.2,
        region: 'North',
        colours: ['#f5a12d', '#003399', '#ffffff'],
        pattern: 'solid',
        stadium: 'Quarry Lane Ground',
        capacity: 9186,
        stature: 3,
      },
      {
        name: 'Milton Keynes Whites',
        reference: 'Milton Keynes Dons',
        city: 'Milton Keynes',
        lat: 52.01,
        lon: -0.733,
        region: 'South',
        colours: ['#ffffff', '#000000', '#d4af37'],
        pattern: 'solid',
        stadium: 'Denbigh Arena',
        capacity: 30500,
        stature: 5,
      },
      {
        name: 'Nottingham Magpies',
        reference: 'Notts County',
        city: 'Nottingham',
        lat: 52.943,
        lon: -1.137,
        region: 'North',
        colours: ['#000000', '#ffffff', '#b39c5d'],
        pattern: 'stripes',
        stadium: 'Trent Meadows Ground',
        capacity: 19841,
        stature: 4,
      },
      {
        name: 'Oxford Yellows',
        reference: 'Oxford United',
        city: 'Oxford',
        lat: 51.716,
        lon: -1.208,
        region: 'South',
        colours: ['#ffe500', '#002147', '#ffffff'],
        pattern: 'solid',
        stadium: 'Grenoble Road Stadium',
        capacity: 12500,
        stature: 6,
      },
      {
        name: 'Peterborough Posh',
        reference: 'Peterborough United',
        city: 'Peterborough',
        lat: 52.565,
        lon: -0.24,
        region: 'North',
        colours: ['#0066b3', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Nene Riverside Ground',
        capacity: 15314,
        stature: 5,
      },
      {
        name: 'Plymouth Pilgrims',
        reference: 'Plymouth Argyle',
        city: 'Plymouth',
        lat: 50.388,
        lon: -4.15,
        region: 'South',
        colours: ['#00573f', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Central Park Ground',
        capacity: 17900,
        stature: 5,
      },
      {
        name: 'Reading Royals',
        reference: 'Reading',
        city: 'Reading',
        lat: 51.422,
        lon: -0.983,
        region: 'South',
        colours: ['#004494', '#ffffff', '#e30613'],
        pattern: 'hoops',
        stadium: 'Kennet Island Stadium',
        capacity: 24161,
        stature: 6,
      },
      {
        name: 'Sheffield Owls',
        reference: 'Sheffield Wednesday',
        city: 'Sheffield',
        lat: 53.411,
        lon: -1.501,
        region: 'North',
        colours: ['#003ca0', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Penistone Road Ground',
        capacity: 39732,
        stature: 7,
      },
      {
        name: 'Stevenage Boro Reds',
        reference: 'Stevenage',
        city: 'Stevenage',
        lat: 51.89,
        lon: -0.193,
        region: 'South',
        colours: ['#e30613', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Broadhall Way Ground',
        capacity: 7800,
        stature: 2,
      },
      {
        name: 'Stockport Hatters',
        reference: 'Stockport County',
        city: 'Stockport',
        lat: 53.4,
        lon: -2.166,
        region: 'North',
        colours: ['#004a9f', '#ffffff', '#e30613'],
        pattern: 'solid',
        stadium: 'Hardcastle Road Ground',
        capacity: 10852,
        stature: 5,
      },
      {
        name: 'Wigan Latics',
        reference: 'Wigan Athletic',
        city: 'Wigan',
        lat: 53.548,
        lon: -2.654,
        region: 'North',
        colours: ['#1d59af', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Robin Park Stadium',
        capacity: 25138,
        stature: 5,
      },
      {
        name: 'Wycombe Chairboys',
        reference: 'Wycombe Wanderers',
        city: 'High Wycombe',
        lat: 51.631,
        lon: -0.8,
        region: 'South',
        colours: ['#88c6ea', '#002d72', '#ffffff'],
        pattern: 'halves',
        stadium: 'Hillbottom Road Ground',
        capacity: 10137,
        stature: 4,
      },
    ],
    4: [
      {
        name: 'Accrington Reds',
        reference: 'Accrington Stanley',
        city: 'Accrington',
        lat: 53.765,
        lon: -2.371,
        region: 'North',
        colours: ['#e21b23', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Livingstone Road Ground',
        capacity: 5450,
        stature: 2,
      },
      {
        name: 'Barnet Ambers',
        reference: 'Barnet',
        city: 'London',
        lat: 51.603,
        lon: -0.293,
        region: 'South',
        colours: ['#f7a823', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Canons Park Ground',
        capacity: 6500,
        stature: 3,
      },
      {
        name: 'Bristol Pirates',
        reference: 'Bristol Rovers',
        city: 'Bristol',
        lat: 51.486,
        lon: -2.583,
        region: 'South',
        colours: ['#0055a4', '#ffffff', '#000000'],
        pattern: 'halves',
        stadium: 'Horfield Stadium',
        capacity: 9832,
        stature: 6,
      },
      {
        name: 'Cheltenham Robins',
        reference: 'Cheltenham Town',
        city: 'Cheltenham',
        lat: 51.906,
        lon: -2.06,
        region: 'South',
        colours: ['#e21a23', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Pittville Ground',
        capacity: 7066,
        stature: 3,
      },
      {
        name: 'Chesterfield Spireites',
        reference: 'Chesterfield',
        city: 'Chesterfield',
        lat: 53.254,
        lon: -1.425,
        region: 'North',
        colours: ['#0050a0', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Whittington Moor Stadium',
        capacity: 10504,
        stature: 6,
      },
      {
        name: 'Colchester Oysters',
        reference: 'Colchester United',
        city: 'Colchester',
        lat: 51.923,
        lon: 0.898,
        region: 'South',
        colours: ['#0055a4', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Cuckoo Farm Stadium',
        capacity: 10105,
        stature: 4,
      },
      {
        name: 'Crawley Red Devils',
        reference: 'Crawley Town',
        city: 'Crawley',
        lat: 51.1,
        lon: -0.195,
        region: 'South',
        colours: ['#e2231a', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Winfield Way Ground',
        capacity: 6134,
        stature: 3,
      },
      {
        name: 'Crewe Railwaymen',
        reference: 'Crewe Alexandra',
        city: 'Crewe',
        lat: 53.087,
        lon: -2.435,
        region: 'North',
        colours: ['#d71920', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Railway Junction Ground',
        capacity: 10153,
        stature: 4,
      },
      {
        name: 'Exeter Grecians',
        reference: 'Exeter City',
        city: 'Exeter',
        lat: 50.731,
        lon: -3.521,
        region: 'South',
        colours: ['#d50032', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Well Street Ground',
        capacity: 8696,
        stature: 5,
      },
      {
        name: 'Fleetwood Cod Army',
        reference: 'Fleetwood Town',
        city: 'Fleetwood',
        lat: 53.917,
        lon: -3.025,
        region: 'North',
        colours: ['#e21b23', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Park Avenue Ground',
        capacity: 5327,
        stature: 3,
      },
      {
        name: 'Gillingham Gills',
        reference: 'Gillingham',
        city: 'Gillingham',
        lat: 51.384,
        lon: 0.561,
        region: 'South',
        colours: ['#0033a0', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Medway Stadium',
        capacity: 11582,
        stature: 4,
      },
      {
        name: 'Grimsby Mariners',
        reference: 'Grimsby Town',
        city: 'Grimsby',
        lat: 53.57,
        lon: -0.046,
        region: 'North',
        colours: ['#000000', '#ffffff', '#e30613'],
        pattern: 'stripes',
        stadium: 'Cleethorpes Seafront Ground',
        capacity: 9052,
        stature: 5,
      },
      {
        name: 'Newport Exiles',
        reference: 'Newport County',
        city: 'Newport',
        lat: 51.588,
        lon: -2.988,
        region: 'South',
        colours: ['#f7a823', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Usk Riverside Ground',
        capacity: 7850,
        stature: 3,
      },
      {
        name: 'Northampton Cobblers',
        reference: 'Northampton Town',
        city: 'Northampton',
        lat: 52.235,
        lon: -0.934,
        region: 'North',
        colours: ['#7a1631', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Upton Way Stadium',
        capacity: 7798,
        stature: 4,
      },
      {
        name: 'Oldham Boundary Blues',
        reference: 'Oldham Athletic',
        city: 'Oldham',
        lat: 53.555,
        lon: -2.129,
        region: 'North',
        colours: ['#004b9b', '#ffffff', '#e30613'],
        pattern: 'solid',
        stadium: 'Sheepfoot Lane Ground',
        capacity: 13513,
        stature: 5,
      },
      {
        name: 'Burslem Valiants',
        reference: 'Port Vale',
        city: 'Stoke-on-Trent',
        lat: 53.05,
        lon: -2.192,
        region: 'North',
        colours: ['#ffffff', '#000000', '#f2c500'],
        pattern: 'solid',
        stadium: 'Hamil Road Ground',
        capacity: 15036,
        stature: 5,
      },
      {
        name: 'Rochdale Pioneers',
        reference: 'Rochdale',
        city: 'Rochdale',
        lat: 53.621,
        lon: -2.18,
        region: 'North',
        colours: ['#0a3d91', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Sandy Lane Ground',
        capacity: 10249,
        stature: 4,
      },
      {
        name: 'Rotherham Millers',
        reference: 'Rotherham United',
        city: 'Rotherham',
        lat: 53.428,
        lon: -1.362,
        region: 'North',
        colours: ['#e21a23', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Don Riverside Stadium',
        capacity: 12021,
        stature: 6,
      },
      {
        name: 'Salford Ammies',
        reference: 'Salford City',
        city: 'Salford',
        lat: 53.513,
        lon: -2.276,
        region: 'North',
        colours: ['#e21a23', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Kersal Moor Ground',
        capacity: 5108,
        stature: 4,
      },
      {
        name: 'Shrewsbury Shrews',
        reference: 'Shrewsbury Town',
        city: 'Shrewsbury',
        lat: 52.689,
        lon: -2.749,
        region: 'North',
        colours: ['#0055a4', '#f7a823', '#ffffff'],
        pattern: 'solid',
        stadium: 'Oteley Road Ground',
        capacity: 9875,
        stature: 4,
      },
      {
        name: 'Swindon Reds',
        reference: 'Swindon Town',
        city: 'Swindon',
        lat: 51.565,
        lon: -1.77,
        region: 'South',
        colours: ['#e21a23', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Shrivenham Road Ground',
        capacity: 15728,
        stature: 5,
      },
      {
        name: 'Wirral Superwhites',
        reference: 'Tranmere Rovers',
        city: 'Birkenhead',
        lat: 53.374,
        lon: -3.033,
        region: 'North',
        colours: ['#ffffff', '#0033a0', '#e30613'],
        pattern: 'solid',
        stadium: 'Borough Road Ground',
        capacity: 16587,
        stature: 4,
      },
      {
        name: 'Walsall Saddlers',
        reference: 'Walsall',
        city: 'Walsall',
        lat: 52.566,
        lon: -1.991,
        region: 'North',
        colours: ['#e21a23', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Tame Valley Stadium',
        capacity: 11300,
        stature: 4,
      },
      {
        name: 'York Minstermen',
        reference: 'York City',
        city: 'York',
        lat: 53.985,
        lon: -1.054,
        region: 'North',
        colours: ['#e21a23', '#002d62', '#ffffff'],
        pattern: 'solid',
        stadium: 'Monks Cross Stadium',
        capacity: 8500,
        stature: 5,
      },
    ],
  },
  towns: {
    North: [
      { name: 'Chester', lat: 53.19, lon: -2.89 },
      { name: 'Southport', lat: 53.65, lon: -3.01 },
      { name: 'Altrincham', lat: 53.39, lon: -2.35 },
      { name: 'Hartlepool', lat: 54.69, lon: -1.21 },
      { name: 'Gateshead', lat: 54.95, lon: -1.6 },
      { name: 'Halifax', lat: 53.72, lon: -1.86 },
      { name: 'Scunthorpe', lat: 53.59, lon: -0.65 },
      { name: 'Darlington', lat: 54.52, lon: -1.55 },
      { name: 'Spennymoor', lat: 54.7, lon: -1.6 },
      { name: 'Kidderminster', lat: 52.39, lon: -2.25 },
      { name: 'Hereford', lat: 52.06, lon: -2.72 },
      { name: 'Buxton', lat: 53.26, lon: -1.91 },
      { name: 'Macclesfield', lat: 53.26, lon: -2.13 },
      { name: 'Kettering', lat: 52.4, lon: -0.73 },
      { name: 'Telford', lat: 52.68, lon: -2.45 },
      { name: 'Alfreton', lat: 53.1, lon: -1.38 },
      { name: 'Chorley', lat: 53.65, lon: -2.63 },
      { name: 'Ashton-under-Lyne', lat: 53.49, lon: -2.1 },
      { name: 'Warrington', lat: 53.39, lon: -2.59 },
      { name: 'Crosby', lat: 53.49, lon: -3.03 },
      { name: 'Radcliffe', lat: 53.56, lon: -2.33 },
      { name: 'Scarborough', lat: 54.28, lon: -0.4 },
      { name: 'Morecambe', lat: 54.07, lon: -2.86 },
      { name: 'Barrow-in-Furness', lat: 54.11, lon: -3.23 },
      { name: 'Harrogate', lat: 53.99, lon: -1.54 },
      { name: 'Tamworth', lat: 52.63, lon: -1.69 },
      { name: 'Boston', lat: 52.98, lon: -0.03 },
      { name: "King's Lynn", lat: 52.75, lon: 0.4 },
      { name: 'Hednesford', lat: 52.71, lon: -2.0 },
      { name: 'Hyde', lat: 53.45, lon: -2.08 },
      { name: 'Stalybridge', lat: 53.48, lon: -2.06 },
      { name: 'Guiseley', lat: 53.88, lon: -1.71 },
      { name: 'Gainsborough', lat: 53.4, lon: -0.77 },
      { name: 'Worksop', lat: 53.3, lon: -1.12 },
      { name: 'Matlock', lat: 53.14, lon: -1.56 },
      { name: 'Leek', lat: 53.1, lon: -2.02 },
      { name: 'Nuneaton', lat: 52.52, lon: -1.47 },
      { name: 'Hinckley', lat: 52.54, lon: -1.37 },
      { name: 'Redditch', lat: 52.31, lon: -1.94 },
      { name: 'Bromsgrove', lat: 52.34, lon: -2.06 },
      { name: 'Stafford', lat: 52.81, lon: -2.12 },
      { name: 'Belper', lat: 53.02, lon: -1.48 },
      { name: 'Ilkeston', lat: 52.97, lon: -1.31 },
      { name: 'Whitby', lat: 54.49, lon: -0.61 },
      { name: 'Blyth', lat: 55.13, lon: -1.51 },
      { name: 'South Shields', lat: 54.99, lon: -1.43 },
      { name: 'Workington', lat: 54.64, lon: -3.55 },
      { name: 'Kendal', lat: 54.33, lon: -2.75 },
      { name: 'Lancaster', lat: 54.05, lon: -2.8 },
      { name: 'Northwich', lat: 53.26, lon: -2.52 },
      { name: 'Nantwich', lat: 53.07, lon: -2.52 },
      { name: 'Runcorn', lat: 53.34, lon: -2.73 },
      { name: 'Mossley', lat: 53.52, lon: -2.04 },
      { name: 'Farsley', lat: 53.81, lon: -1.67 },
      { name: 'Ossett', lat: 53.68, lon: -1.58 },
      { name: 'Brighouse', lat: 53.7, lon: -1.78 },
      { name: 'Spalding', lat: 52.79, lon: -0.15 },
      { name: 'Stamford', lat: 52.65, lon: -0.48 },
      { name: 'Corby', lat: 52.49, lon: -0.7 },
      { name: 'Coalville', lat: 52.72, lon: -1.37 },
      { name: 'Loughborough', lat: 52.77, lon: -1.2 },
      { name: 'Sutton Coldfield', lat: 52.56, lon: -1.82 },
      { name: 'Solihull', lat: 52.41, lon: -1.78 },
      { name: 'Leamington', lat: 52.29, lon: -1.53 },
      { name: 'Rugby', lat: 52.37, lon: -1.26 },
      { name: 'Worcester', lat: 52.19, lon: -2.22 },
      { name: 'Stourbridge', lat: 52.46, lon: -2.15 },
      { name: 'Halesowen', lat: 52.45, lon: -2.05 },
      { name: 'Consett', lat: 54.85, lon: -1.83 },
      { name: 'Bishop Auckland', lat: 54.66, lon: -1.68 },
      { name: 'Morpeth', lat: 55.17, lon: -1.69 },
      { name: 'Stockton-on-Tees', lat: 54.57, lon: -1.32 },
      { name: 'Glossop', lat: 53.44, lon: -1.95 },
      { name: 'Skelmersdale', lat: 53.55, lon: -2.78 },
    ],
    South: [
      { name: 'Aldershot', lat: 51.25, lon: -0.76 },
      { name: 'Woking', lat: 51.32, lon: -0.56 },
      { name: 'Sutton', lat: 51.36, lon: -0.19 },
      { name: 'Dagenham', lat: 51.54, lon: 0.15 },
      { name: 'Eastleigh', lat: 50.97, lon: -1.35 },
      { name: 'Maidenhead', lat: 51.52, lon: -0.72 },
      { name: 'Dorking', lat: 51.23, lon: -0.33 },
      { name: 'Borehamwood', lat: 51.66, lon: -0.27 },
      { name: 'Northfleet', lat: 51.44, lon: 0.33 },
      { name: 'Yeovil', lat: 50.94, lon: -2.63 },
      { name: 'Nailsworth', lat: 51.69, lon: -2.22 },
      { name: 'Braintree', lat: 51.88, lon: 0.55 },
      { name: 'Dartford', lat: 51.44, lon: 0.21 },
      { name: 'Maidstone', lat: 51.27, lon: 0.52 },
      { name: 'Bath', lat: 51.38, lon: -2.36 },
      { name: 'Weston-super-Mare', lat: 51.35, lon: -2.98 },
      { name: 'Chelmsford', lat: 51.74, lon: 0.47 },
      { name: 'Hampton', lat: 51.41, lon: -0.37 },
      { name: 'Slough', lat: 51.51, lon: -0.59 },
      { name: 'Hemel Hempstead', lat: 51.75, lon: -0.47 },
      { name: 'St Albans', lat: 51.75, lon: -0.34 },
      { name: 'Welling', lat: 51.46, lon: 0.11 },
      { name: 'Tonbridge', lat: 51.2, lon: 0.27 },
      { name: 'Worthing', lat: 50.81, lon: -0.37 },
      { name: 'Farnborough', lat: 51.29, lon: -0.75 },
      { name: 'Chippenham', lat: 51.46, lon: -2.12 },
      { name: 'Truro', lat: 50.26, lon: -5.05 },
      { name: 'Enfield', lat: 51.65, lon: -0.08 },
      { name: 'Hornchurch', lat: 51.56, lon: 0.22 },
      { name: 'Torquay', lat: 50.46, lon: -3.53 },
      { name: 'Salisbury', lat: 51.07, lon: -1.79 },
      { name: 'Weymouth', lat: 50.61, lon: -2.46 },
      { name: 'Dover', lat: 51.13, lon: 1.31 },
      { name: 'Folkestone', lat: 51.08, lon: 1.17 },
      { name: 'Hastings', lat: 50.86, lon: 0.57 },
      { name: 'Eastbourne', lat: 50.77, lon: 0.28 },
      { name: 'Bognor Regis', lat: 50.78, lon: -0.68 },
      { name: 'Havant', lat: 50.85, lon: -0.98 },
      { name: 'Gosport', lat: 50.79, lon: -1.13 },
      { name: 'Chesham', lat: 51.71, lon: -0.61 },
      { name: 'Hitchin', lat: 51.95, lon: -0.28 },
      { name: "Bishop's Stortford", lat: 51.87, lon: 0.16 },
      { name: 'Billericay', lat: 51.63, lon: 0.42 },
      { name: 'Canvey Island', lat: 51.52, lon: 0.58 },
      { name: 'Chatham', lat: 51.38, lon: 0.53 },
      { name: 'Margate', lat: 51.39, lon: 1.39 },
      { name: 'Taunton', lat: 51.02, lon: -3.1 },
      { name: 'Gloucester', lat: 51.86, lon: -2.24 },
      { name: 'Banbury', lat: 52.06, lon: -1.34 },
      { name: 'Hungerford', lat: 51.41, lon: -1.52 },
      { name: 'Basingstoke', lat: 51.27, lon: -1.09 },
      { name: 'Bracknell', lat: 51.41, lon: -0.75 },
      { name: 'Aylesbury', lat: 51.82, lon: -0.81 },
      { name: 'Lowestoft', lat: 52.48, lon: 1.75 },
      { name: 'Bury St Edmunds', lat: 52.25, lon: 0.71 },
      { name: 'Needham Market', lat: 52.15, lon: 1.05 },
      { name: 'Brentwood', lat: 51.62, lon: 0.3 },
      { name: 'Harlow', lat: 51.77, lon: 0.09 },
      { name: 'Cheshunt', lat: 51.71, lon: -0.03 },
      { name: 'Royston', lat: 52.05, lon: -0.02 },
      { name: 'Bedford', lat: 52.14, lon: -0.47 },
      { name: 'Kingston upon Thames', lat: 51.41, lon: -0.3 },
      { name: 'Walton-on-Thames', lat: 51.39, lon: -0.42 },
      { name: 'Horsham', lat: 51.06, lon: -0.33 },
      { name: 'Lewes', lat: 50.87, lon: 0.01 },
      { name: 'Merthyr Tydfil', lat: 51.75, lon: -3.38 },
      { name: 'Poole', lat: 50.72, lon: -1.98 },
      { name: 'Dorchester', lat: 50.71, lon: -2.44 },
      { name: 'Tiverton', lat: 50.9, lon: -3.49 },
    ],
  },
  groupRegions: { 5: [['North', 'South']], 6: [['North'], ['South']] },
};
