import type { CountryIdentity } from './types';

/**
 * France: Ligue 1 and Ligue 2 memberships for 2026/27 (after the 2025/26 promotions,
 * relegations and barrages). Ligue 3 and National 1 are filled with generated clubs.
 */
export const FRANCE: CountryIdentity = {
  counterpart: 'France',
  name: 'France',
  adjective: 'French',
  divisions: {
    1: { name: 'French Première Division', reference: 'Ligue 1' },
    2: { name: 'French Deuxième Division', reference: 'Ligue 2' },
    3: { name: 'French Troisième Division', reference: 'Ligue 3' },
    4: {
      name: 'French National Division',
      reference: 'National 1',
      groups: ['North-West', 'North-East', 'South'],
    },
  },
  cup: { name: 'French National Cup', reference: 'Coupe de France' },
  clubs: {
    1: [
      {
        name: 'Paris Capitals',
        reference: 'Paris Saint-Germain',
        city: 'Paris',
        lat: 48.84,
        lon: 2.25,
        region: 'Northwest',
        colours: ['#004170', '#da291c', '#ffffff'],
        pattern: 'solid',
        stadium: 'Parc Royal',
        capacity: 47929,
        stature: 10,
      },
      {
        name: 'Marseille Phocaeans',
        reference: 'Olympique de Marseille',
        city: 'Marseille',
        lat: 43.27,
        lon: 5.4,
        region: 'South',
        colours: ['#ffffff', '#2faee0', '#0b2a4a'],
        pattern: 'solid',
        stadium: 'Le Grand Anneau',
        capacity: 67394,
        stature: 9,
      },
      {
        name: 'Lyon Lions',
        reference: 'Olympique Lyonnais',
        city: 'Lyon',
        lat: 45.76,
        lon: 4.84,
        region: 'South',
        colours: ['#ffffff', '#1d3f8f', '#da291c'],
        pattern: 'solid',
        stadium: 'Lumières Arena',
        capacity: 59186,
        stature: 8,
      },
      {
        name: 'Monaco Red & White',
        reference: 'AS Monaco',
        city: 'Monaco',
        lat: 43.73,
        lon: 7.42,
        region: 'South',
        colours: ['#e2001a', '#ffffff', '#c9a227'],
        pattern: 'halves',
        stadium: 'Stade de Fontvieille',
        capacity: 16360,
        stature: 8,
      },
      {
        name: 'Lille Mastiffs',
        reference: 'Lille OSC',
        city: 'Lille',
        lat: 50.63,
        lon: 3.06,
        region: 'Northeast',
        colours: ['#e01e13', '#1c2a4d', '#ffffff'],
        pattern: 'solid',
        stadium: 'Grand Stade de Flandre',
        capacity: 50186,
        stature: 8,
      },
      {
        name: 'Lens Blood & Gold',
        reference: 'RC Lens',
        city: 'Lens',
        lat: 50.43,
        lon: 2.83,
        region: 'Northeast',
        colours: ['#f6c600', '#e2001a', '#000000'],
        pattern: 'solid',
        stadium: 'Stade des Mineurs',
        capacity: 38223,
        stature: 7,
      },
      {
        name: 'Nice Eaglets',
        reference: 'OGC Nice',
        city: 'Nice',
        lat: 43.7,
        lon: 7.27,
        region: 'South',
        colours: ['#c8102e', '#000000', '#ffffff'],
        pattern: 'stripes',
        stadium: 'Stade du Var',
        capacity: 36178,
        stature: 7,
      },
      {
        name: 'Rennes Red & Black',
        reference: 'Stade Rennais',
        city: 'Rennes',
        lat: 48.11,
        lon: -1.68,
        region: 'Northwest',
        colours: ['#e13327', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Parc de la Vilaine',
        capacity: 29778,
        stature: 7,
      },
      {
        name: 'Strasbourg Storks',
        reference: 'RC Strasbourg Alsace',
        city: 'Strasbourg',
        lat: 48.58,
        lon: 7.75,
        region: 'Northeast',
        colours: ['#0a8fd8', '#ffffff', '#e30613'],
        pattern: 'solid',
        stadium: "Stade de l'Ill",
        capacity: 26280,
        stature: 6,
      },
      {
        name: 'Paris Navy Blues',
        reference: 'Paris FC',
        city: 'Paris',
        lat: 48.84,
        lon: 2.25,
        region: 'Northwest',
        colours: ['#1b2a4a', '#ffffff', '#6cace4'],
        pattern: 'solid',
        stadium: "Stade d'Auteuil",
        capacity: 19904,
        stature: 5,
      },
      {
        name: 'Toulouse Violets',
        reference: 'Toulouse FC',
        city: 'Toulouse',
        lat: 43.6,
        lon: 1.44,
        region: 'South',
        colours: ['#5b2c83', '#ffffff', '#c9b6e4'],
        pattern: 'solid',
        stadium: 'Stade du Ramier',
        capacity: 33150,
        stature: 5,
      },
      {
        name: 'Brest Pirates',
        reference: 'Stade Brestois 29',
        city: 'Brest',
        lat: 48.39,
        lon: -4.49,
        region: 'Northwest',
        colours: ['#e30613', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Stade de la Rade',
        capacity: 15220,
        stature: 5,
      },
      {
        name: 'Lorient Hakes',
        reference: 'FC Lorient',
        city: 'Lorient',
        lat: 47.75,
        lon: -3.37,
        region: 'Northwest',
        colours: ['#f58220', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Stade du Port',
        capacity: 18890,
        stature: 3,
      },
      {
        name: 'Auxerre Blue & White',
        reference: 'AJ Auxerre',
        city: 'Auxerre',
        lat: 47.8,
        lon: 3.57,
        region: 'Northeast',
        colours: ['#ffffff', '#00539f', '#d4af37'],
        pattern: 'solid',
        stadium: "The Abbot's Field",
        capacity: 18541,
        stature: 3,
      },
      {
        name: 'Angers Black & White',
        reference: 'Angers SCO',
        city: 'Angers',
        lat: 47.47,
        lon: -0.55,
        region: 'Northwest',
        colours: ['#000000', '#ffffff', '#c8a951'],
        pattern: 'stripes',
        stadium: 'Stade Napoléon',
        capacity: 19350,
        stature: 3,
      },
      {
        name: 'Le Havre Sky & Navy',
        reference: 'Le Havre AC',
        city: 'Le Havre',
        lat: 49.49,
        lon: 0.11,
        region: 'Northwest',
        colours: ['#8ac6ea', '#1d2b4f', '#ffffff'],
        pattern: 'halves',
        stadium: 'Stade des Docks',
        capacity: 25178,
        stature: 3,
      },
      {
        name: 'Troyes Champagne Blues',
        reference: 'ES Troyes AC',
        city: 'Troyes',
        lat: 48.3,
        lon: 4.07,
        region: 'Northeast',
        colours: ['#003da5', '#ffffff', '#6cace4'],
        pattern: 'solid',
        stadium: 'Stade de la Seine',
        capacity: 21684,
        stature: 2,
      },
      {
        name: 'Le Mans Racers',
        reference: 'Le Mans FC',
        city: 'Le Mans',
        lat: 48.0,
        lon: 0.2,
        region: 'Northwest',
        colours: ['#d71920', '#ffd200', '#000000'],
        pattern: 'solid',
        stadium: 'Circuit Arena',
        capacity: 25064,
        stature: 2,
      },
    ],
    2: [
      {
        name: 'Saint-Étienne Greens',
        reference: 'AS Saint-Étienne',
        city: 'Saint-Étienne',
        lat: 45.44,
        lon: 4.39,
        region: 'South',
        colours: ['#009a44', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Le Chaudron Vert',
        capacity: 41965,
        stature: 10,
      },
      {
        name: 'Nantes Canaries',
        reference: 'FC Nantes',
        city: 'Nantes',
        lat: 47.22,
        lon: -1.55,
        region: 'Northwest',
        colours: ['#fcd405', '#00954c', '#ffffff'],
        pattern: 'solid',
        stadium: "Stade de l'Erdre",
        capacity: 35322,
        stature: 9,
      },
      {
        name: 'Montpellier Paillade',
        reference: 'Montpellier HSC',
        city: 'Montpellier',
        lat: 43.61,
        lon: 3.88,
        region: 'South',
        colours: ['#003c71', '#f47920', '#ffffff'],
        pattern: 'solid',
        stadium: 'Stade du Lez',
        capacity: 32900,
        stature: 8,
      },
      {
        name: 'Metz Garnets',
        reference: 'FC Metz',
        city: 'Metz',
        lat: 49.12,
        lon: 6.18,
        region: 'Northeast',
        colours: ['#8b1d2c', '#ffffff', '#c9a227'],
        pattern: 'solid',
        stadium: 'Stade de la Moselle',
        capacity: 28786,
        stature: 8,
      },
      {
        name: 'Reims Champagne Reds',
        reference: 'Stade de Reims',
        city: 'Reims',
        lat: 49.25,
        lon: 4.03,
        region: 'Northeast',
        colours: ['#e2001a', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Stade des Sacres',
        capacity: 21029,
        stature: 8,
      },
      {
        name: 'Sochaux Lion Cubs',
        reference: 'FC Sochaux-Montbéliard',
        city: 'Sochaux',
        lat: 47.51,
        lon: 6.83,
        region: 'Northeast',
        colours: ['#ffd100', '#0a2d6e', '#ffffff'],
        pattern: 'solid',
        stadium: "Stade de l'Allan",
        capacity: 20005,
        stature: 6,
      },
      {
        name: 'Nancy Thistles',
        reference: 'AS Nancy Lorraine',
        city: 'Nancy',
        lat: 48.69,
        lon: 6.18,
        region: 'Northeast',
        colours: ['#e2001a', '#ffffff', '#8a8d8f'],
        pattern: 'solid',
        stadium: 'Stade de la Meurthe',
        capacity: 20087,
        stature: 6,
      },
      {
        name: 'Guingamp Forward',
        reference: 'En Avant Guingamp',
        city: 'Guingamp',
        lat: 48.56,
        lon: -3.15,
        region: 'Northwest',
        colours: ['#e2001a', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Stade du Trieux',
        capacity: 18378,
        stature: 5,
      },
      {
        name: 'Grenoble Alpine Blues',
        reference: 'Grenoble Foot 38',
        city: 'Grenoble',
        lat: 45.19,
        lon: 5.72,
        region: 'South',
        colours: ['#0055a4', '#ffffff', '#e2001a'],
        pattern: 'solid',
        stadium: "Stade de l'Isère",
        capacity: 20068,
        stature: 5,
      },
      {
        name: 'Clermont Volcanoes',
        reference: 'Clermont Foot 63',
        city: 'Clermont-Ferrand',
        lat: 45.78,
        lon: 3.08,
        region: 'South',
        colours: ['#b51f2d', '#003a70', '#ffffff'],
        pattern: 'halves',
        stadium: 'Stade des Puys',
        capacity: 11980,
        stature: 5,
      },
      {
        name: 'Dijon Owls',
        reference: 'Dijon FCO',
        city: 'Dijon',
        lat: 47.32,
        lon: 5.04,
        region: 'Northeast',
        colours: ['#d4021d', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Stade des Ducs',
        capacity: 15995,
        stature: 5,
      },
      {
        name: 'Laval Tangos',
        reference: 'Stade Lavallois',
        city: 'Laval',
        lat: 48.07,
        lon: -0.77,
        region: 'Northwest',
        colours: ['#f39200', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Stade de la Mayenne',
        capacity: 18607,
        stature: 4,
      },
      {
        name: 'Annecy Alpine Reds',
        reference: 'FC Annecy',
        city: 'Annecy',
        lat: 45.9,
        lon: 6.13,
        region: 'South',
        colours: ['#e2001a', '#ffffff', '#1d2b4f'],
        pattern: 'solid',
        stadium: 'Stade du Lac',
        capacity: 15660,
        stature: 4,
      },
      {
        name: 'Saint-Ouen Stars',
        reference: 'Red Star FC',
        city: 'Saint-Ouen-sur-Seine',
        lat: 48.91,
        lon: 2.33,
        region: 'Northeast',
        colours: ['#00843d', '#ffffff', '#e2001a'],
        pattern: 'solid',
        stadium: 'Stade des Puces',
        capacity: 10000,
        stature: 4,
      },
      {
        name: 'Pau Pyrenees',
        reference: 'Pau FC',
        city: 'Pau',
        lat: 43.3,
        lon: -0.37,
        region: 'South',
        colours: ['#ffd200', '#003b7a', '#ffffff'],
        pattern: 'solid',
        stadium: 'Stade du Béarn',
        capacity: 4031,
        stature: 3,
      },
      {
        name: 'Rodez Ruthenians',
        reference: 'Rodez AF',
        city: 'Rodez',
        lat: 44.35,
        lon: 2.57,
        region: 'South',
        colours: ['#c8102e', '#f6c600', '#000000'],
        pattern: 'solid',
        stadium: "Stade de l'Aveyron",
        capacity: 5955,
        stature: 3,
      },
      {
        name: 'Dunkerque Mariners',
        reference: 'USL Dunkerque',
        city: 'Dunkerque',
        lat: 51.03,
        lon: 2.38,
        region: 'Northeast',
        colours: ['#003da5', '#ffffff', '#e2001a'],
        pattern: 'solid',
        stadium: 'Stade de la Digue',
        capacity: 4933,
        stature: 3,
      },
      {
        name: 'Boulogne Fishermen',
        reference: 'US Boulogne',
        city: 'Boulogne-sur-Mer',
        lat: 50.73,
        lon: 1.61,
        region: 'Northeast',
        colours: ['#e2001a', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Stade du Port de Pêche',
        capacity: 9534,
        stature: 2,
      },
    ],
  },
  groupRegions: {
    3: [['Northwest', 'Northeast', 'South']],
    4: [['Northwest'], ['Northeast'], ['South']],
  },
  towns: {
    Northwest: [
      { name: 'Rouen', lat: 49.44, lon: 1.1 },
      { name: 'Caen', lat: 49.18, lon: -0.37 },
      { name: 'Le Petit-Quevilly', lat: 49.43, lon: 1.06 },
      { name: 'Cherbourg-en-Cotentin', lat: 49.64, lon: -1.62 },
      { name: 'Avranches', lat: 48.68, lon: -1.36 },
      { name: 'Saint-Malo', lat: 48.65, lon: -2.01 },
      { name: 'Vannes', lat: 47.66, lon: -2.76 },
      { name: 'Quimper', lat: 48.0, lon: -4.1 },
      { name: 'Concarneau', lat: 47.87, lon: -3.92 },
      { name: 'Saint-Brieuc', lat: 48.51, lon: -2.76 },
      { name: 'Lannion', lat: 48.73, lon: -3.46 },
      { name: 'Vitré', lat: 48.12, lon: -1.21 },
      { name: 'Fougères', lat: 48.35, lon: -1.2 },
      { name: 'Saint-Nazaire', lat: 47.27, lon: -2.21 },
      { name: 'Cholet', lat: 47.06, lon: -0.88 },
      { name: 'La Roche-sur-Yon', lat: 46.67, lon: -1.43 },
      { name: "Les Sables-d'Olonne", lat: 46.5, lon: -1.78 },
      { name: 'Les Herbiers', lat: 46.87, lon: -1.01 },
      { name: 'Saumur', lat: 47.26, lon: -0.08 },
      { name: 'Tours', lat: 47.39, lon: 0.69 },
      { name: 'Orléans', lat: 47.9, lon: 1.9 },
      { name: 'Blois', lat: 47.59, lon: 1.33 },
      { name: 'Chartres', lat: 48.45, lon: 1.49 },
      { name: 'Bourges', lat: 47.08, lon: 2.4 },
      { name: 'Châteauroux', lat: 46.81, lon: 1.69 },
      { name: 'Vierzon', lat: 47.22, lon: 2.07 },
      { name: 'Dreux', lat: 48.74, lon: 1.37 },
      { name: 'Évreux', lat: 49.02, lon: 1.15 },
      { name: 'Alençon', lat: 48.43, lon: 0.09 },
      { name: 'Lisieux', lat: 49.15, lon: 0.23 },
      { name: 'Dieppe', lat: 49.92, lon: 1.08 },
      { name: 'Fécamp', lat: 49.76, lon: 0.37 },
      { name: 'Granville', lat: 48.84, lon: -1.6 },
      { name: 'Saint-Lô', lat: 49.12, lon: -1.09 },
      { name: 'Versailles', lat: 48.8, lon: 2.13 },
      { name: 'Poissy', lat: 48.93, lon: 2.05 },
      { name: 'Mantes-la-Jolie', lat: 48.99, lon: 1.72 },
      { name: 'Saint-Germain-en-Laye', lat: 48.9, lon: 2.09 },
      { name: 'Boulogne-Billancourt', lat: 48.84, lon: 2.24 },
      { name: 'Nanterre', lat: 48.89, lon: 2.21 },
      { name: 'Pontivy', lat: 48.07, lon: -2.96 },
      { name: 'Morlaix', lat: 48.58, lon: -3.83 },
      { name: 'Dinan', lat: 48.45, lon: -2.05 },
      { name: 'Sablé-sur-Sarthe', lat: 47.84, lon: -0.33 },
      { name: 'Château-Gontier', lat: 47.83, lon: -0.7 },
      { name: 'Montargis', lat: 48.0, lon: 2.73 },
    ],
    Northeast: [
      { name: 'Amiens', lat: 49.89, lon: 2.3 },
      { name: 'Valenciennes', lat: 50.36, lon: 3.52 },
      { name: 'Calais', lat: 50.95, lon: 1.86 },
      { name: 'Arras', lat: 50.29, lon: 2.78 },
      { name: 'Béthune', lat: 50.53, lon: 2.64 },
      { name: 'Douai', lat: 50.37, lon: 3.08 },
      { name: 'Cambrai', lat: 50.18, lon: 3.24 },
      { name: 'Maubeuge', lat: 50.28, lon: 3.97 },
      { name: 'Saint-Quentin', lat: 49.85, lon: 3.29 },
      { name: 'Beauvais', lat: 49.43, lon: 2.08 },
      { name: 'Compiègne', lat: 49.42, lon: 2.83 },
      { name: 'Chambly', lat: 49.17, lon: 2.25 },
      { name: 'Soissons', lat: 49.38, lon: 3.32 },
      { name: 'Roubaix', lat: 50.69, lon: 3.18 },
      { name: 'Tourcoing', lat: 50.72, lon: 3.16 },
      { name: 'Épinal', lat: 48.17, lon: 6.45 },
      { name: 'Thionville', lat: 49.36, lon: 6.17 },
      { name: 'Sarreguemines', lat: 49.11, lon: 7.07 },
      { name: 'Forbach', lat: 49.19, lon: 6.9 },
      { name: 'Colmar', lat: 48.08, lon: 7.36 },
      { name: 'Mulhouse', lat: 47.75, lon: 7.34 },
      { name: 'Haguenau', lat: 48.82, lon: 7.79 },
      { name: 'Schiltigheim', lat: 48.61, lon: 7.75 },
      { name: 'Charleville-Mézières', lat: 49.77, lon: 4.72 },
      { name: 'Sedan', lat: 49.7, lon: 4.94 },
      { name: 'Châlons-en-Champagne', lat: 48.96, lon: 4.36 },
      { name: 'Épernay', lat: 49.04, lon: 3.96 },
      { name: 'Chaumont', lat: 48.11, lon: 5.14 },
      { name: 'Saint-Dizier', lat: 48.64, lon: 4.95 },
      { name: 'Besançon', lat: 47.24, lon: 6.02 },
      { name: 'Belfort', lat: 47.64, lon: 6.86 },
      { name: 'Montbéliard', lat: 47.51, lon: 6.8 },
      { name: 'Dole', lat: 47.09, lon: 5.49 },
      { name: 'Lons-le-Saunier', lat: 46.67, lon: 5.55 },
      { name: 'Chalon-sur-Saône', lat: 46.78, lon: 4.85 },
      { name: 'Mâcon', lat: 46.31, lon: 4.83 },
      { name: 'Nevers', lat: 46.99, lon: 3.16 },
      { name: 'Sens', lat: 48.2, lon: 3.28 },
      { name: 'Créteil', lat: 48.79, lon: 2.46 },
      { name: 'Bobigny', lat: 48.91, lon: 2.44 },
      { name: 'Saint-Maur-des-Fossés', lat: 48.8, lon: 2.49 },
      { name: 'Meaux', lat: 48.96, lon: 2.88 },
      { name: 'Melun', lat: 48.54, lon: 2.66 },
      { name: 'Lunéville', lat: 48.59, lon: 6.5 },
      { name: 'Verdun', lat: 49.16, lon: 5.38 },
      { name: 'Pontarlier', lat: 46.9, lon: 6.35 },
    ],
    South: [
      { name: 'Bordeaux', lat: 44.84, lon: -0.58 },
      { name: 'Ajaccio', lat: 41.92, lon: 8.74 },
      { name: 'Bastia', lat: 42.7, lon: 9.45 },
      { name: 'Niort', lat: 46.32, lon: -0.46 },
      { name: 'Poitiers', lat: 46.58, lon: 0.34 },
      { name: 'Limoges', lat: 45.83, lon: 1.26 },
      { name: 'La Rochelle', lat: 46.16, lon: -1.15 },
      { name: 'Angoulême', lat: 45.65, lon: 0.16 },
      { name: 'Bayonne', lat: 43.49, lon: -1.47 },
      { name: 'Mont-de-Marsan', lat: 43.89, lon: -0.5 },
      { name: 'Agen', lat: 44.2, lon: 0.62 },
      { name: 'Périgueux', lat: 45.18, lon: 0.72 },
      { name: 'Bergerac', lat: 44.85, lon: 0.48 },
      { name: 'Brive-la-Gaillarde', lat: 45.16, lon: 1.53 },
      { name: 'Albi', lat: 43.93, lon: 2.15 },
      { name: 'Castres', lat: 43.61, lon: 2.24 },
      { name: 'Béziers', lat: 43.34, lon: 3.22 },
      { name: 'Sète', lat: 43.4, lon: 3.7 },
      { name: 'Nîmes', lat: 43.84, lon: 4.36 },
      { name: 'Narbonne', lat: 43.18, lon: 3.0 },
      { name: 'Perpignan', lat: 42.7, lon: 2.9 },
      { name: 'Carcassonne', lat: 43.21, lon: 2.35 },
      { name: 'Tarbes', lat: 43.23, lon: 0.08 },
      { name: 'Montauban', lat: 44.02, lon: 1.35 },
      { name: 'Avignon', lat: 43.95, lon: 4.81 },
      { name: 'Toulon', lat: 43.12, lon: 5.93 },
      { name: 'Fréjus', lat: 43.43, lon: 6.74 },
      { name: 'Cannes', lat: 43.55, lon: 7.01 },
      { name: 'Hyères', lat: 43.12, lon: 6.13 },
      { name: 'Martigues', lat: 43.4, lon: 5.05 },
      { name: 'Aubagne', lat: 43.29, lon: 5.57 },
      { name: 'Aix-en-Provence', lat: 43.53, lon: 5.45 },
      { name: 'Marignane', lat: 43.42, lon: 5.21 },
      { name: 'Istres', lat: 43.51, lon: 4.99 },
      { name: 'Gap', lat: 44.56, lon: 6.08 },
      { name: 'Valence', lat: 44.93, lon: 4.89 },
      { name: 'Bourg-en-Bresse', lat: 46.21, lon: 5.23 },
      { name: 'Villefranche-sur-Saône', lat: 45.99, lon: 4.72 },
      { name: 'Le Puy-en-Velay', lat: 45.04, lon: 3.88 },
      { name: 'Aurillac', lat: 44.93, lon: 2.44 },
      { name: 'Vichy', lat: 46.13, lon: 3.43 },
      { name: 'Montluçon', lat: 46.34, lon: 2.6 },
      { name: 'Chambéry', lat: 45.56, lon: 5.92 },
      { name: 'Thonon-les-Bains', lat: 46.37, lon: 6.48 },
      { name: 'Annemasse', lat: 46.19, lon: 6.24 },
      { name: 'Roanne', lat: 46.04, lon: 4.07 },
    ],
  },
};
