import type { CountryIdentity } from './types';

/**
 * Portugal: fictional clubs referencing the real 2026/27 Liga Portugal and Liga Portugal 2
 * memberships; Liga 3 and Campeonato de Portugal are filled with generated clubs in real towns.
 */
export const PORTUGAL: CountryIdentity = {
  counterpart: 'Portugal',
  name: 'Portugal',
  adjective: 'Portuguese',
  divisions: {
    1: { name: 'Portuguese Primeira', reference: 'Liga Portugal' },
    2: { name: 'Portuguese Segunda', reference: 'Liga Portugal 2' },
    3: { name: 'Portuguese Terceira', reference: 'Liga 3', groups: ['North', 'South'] },
    4: {
      name: 'Portuguese National Championship',
      reference: 'Campeonato de Portugal',
      groups: ['Series A', 'Series B', 'Series C', 'Series D'],
    },
  },
  cup: { name: 'Portuguese National Cup', reference: 'Taça de Portugal' },
  clubs: {
    1: [
      {
        name: 'Lisbon Eagles',
        reference: 'Benfica',
        city: 'Lisbon',
        lat: 38.75,
        lon: -9.18,
        region: 'South-central',
        colours: ['#e30613', '#ffffff', '#1a1a1a'],
        pattern: 'solid',
        stadium: 'Cathedral Eagle Stadium',
        capacity: 68100,
        stature: 10,
      },
      {
        name: 'Lisbon Lions',
        reference: 'Sporting CP',
        city: 'Lisbon',
        lat: 38.76,
        lon: -9.16,
        region: 'South-central',
        colours: ['#008057', '#ffffff', '#000000'],
        pattern: 'hoops',
        stadium: 'Green Lions Arena',
        capacity: 52095,
        stature: 10,
      },
      {
        name: 'Porto Dragons',
        reference: 'FC Porto',
        city: 'Porto',
        lat: 41.16,
        lon: -8.58,
        region: 'North',
        colours: ['#003c8f', '#ffffff', '#f2c400'],
        pattern: 'stripes',
        stadium: "Dragon's Lair Stadium",
        capacity: 50033,
        stature: 10,
      },
      {
        name: 'Braga Warriors',
        reference: 'Braga',
        city: 'Braga',
        lat: 41.56,
        lon: -8.43,
        region: 'North',
        colours: ['#e2001a', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Quarry Rock Stadium',
        capacity: 30286,
        stature: 8,
      },
      {
        name: 'Guimarães Conquerors',
        reference: 'Vitória SC',
        city: 'Guimarães',
        lat: 41.45,
        lon: -8.3,
        region: 'North',
        colours: ['#ffffff', '#000000', '#c8a000'],
        pattern: 'solid',
        stadium: "First King's Ground",
        capacity: 30029,
        stature: 7,
      },
      {
        name: 'Famalicão Blues',
        reference: 'Famalicão',
        city: 'Vila Nova de Famalicão',
        lat: 41.41,
        lon: -8.52,
        region: 'North',
        colours: ['#0047ab', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Famalicão Civic Stadium',
        capacity: 5186,
        stature: 6,
      },
      {
        name: 'Barcelos Roosters',
        reference: 'Gil Vicente',
        city: 'Barcelos',
        lat: 41.54,
        lon: -8.6,
        region: 'North',
        colours: ['#e30613', '#0033a0', '#ffffff'],
        pattern: 'solid',
        stadium: 'Rooster City Stadium',
        capacity: 12046,
        stature: 6,
      },
      {
        name: 'Ponta Delgada Islanders',
        reference: 'Santa Clara',
        city: 'Ponta Delgada',
        lat: 37.75,
        lon: -25.67,
        region: 'South',
        colours: ['#e30613', '#ffffff', '#1a1a1a'],
        pattern: 'solid',
        stadium: 'Atlantic Isle Stadium',
        capacity: 12500,
        stature: 5,
      },
      {
        name: 'Estoril Canaries',
        reference: 'Estoril Praia',
        city: 'Estoril',
        lat: 38.71,
        lon: -9.4,
        region: 'South-central',
        colours: ['#ffd700', '#0047ab', '#ffffff'],
        pattern: 'solid',
        stadium: 'Riviera Coast Ground',
        capacity: 5094,
        stature: 5,
      },
      {
        name: 'Moreira Canons',
        reference: 'Moreirense',
        city: 'Moreira de Cónegos',
        lat: 41.38,
        lon: -8.36,
        region: 'North',
        colours: ['#008a3e', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: "Canons' Hill Ground",
        capacity: 6150,
        stature: 5,
      },
      {
        name: 'Vila do Conde Riversiders',
        reference: 'Rio Ave',
        city: 'Vila do Conde',
        lat: 41.36,
        lon: -8.74,
        region: 'North',
        colours: ['#007a3d', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Ave Riverside Ground',
        capacity: 5300,
        stature: 4,
      },
      {
        name: 'Lisbon Geese',
        reference: 'Casa Pia',
        city: 'Lisbon',
        lat: 38.71,
        lon: -9.2,
        region: 'South-central',
        colours: ['#000000', '#ffffff', '#7a7a7a'],
        pattern: 'solid',
        stadium: 'Geese Pond Ground',
        capacity: 7000,
        stature: 4,
      },
      {
        name: 'Arouca Mountaineers',
        reference: 'Arouca',
        city: 'Arouca',
        lat: 40.93,
        lon: -8.25,
        region: 'North-central',
        colours: ['#ffd700', '#003da5', '#ffffff'],
        pattern: 'solid',
        stadium: 'Freita Mountain Ground',
        capacity: 5000,
        stature: 4,
      },
      {
        name: 'Funchal Mariners',
        reference: 'Marítimo',
        city: 'Funchal',
        lat: 32.65,
        lon: -16.93,
        region: 'South',
        colours: ['#e30613', '#007a3d', '#ffffff'],
        pattern: 'halves',
        stadium: 'Barreiros Harbour Stadium',
        capacity: 10600,
        stature: 4,
      },
      {
        name: 'Amadora Stars',
        reference: 'Estrela da Amadora',
        city: 'Amadora',
        lat: 38.75,
        lon: -9.22,
        region: 'South-central',
        colours: ['#e30613', '#007a3d', '#ffffff'],
        pattern: 'stripes',
        stadium: 'Reboleira Star Park',
        capacity: 9288,
        stature: 3,
      },
      {
        name: 'Funchal Magpies',
        reference: 'Nacional',
        city: 'Funchal',
        lat: 32.67,
        lon: -16.89,
        region: 'South',
        colours: ['#000000', '#ffffff', '#c8a000'],
        pattern: 'stripes',
        stadium: 'Choupana Heights Stadium',
        capacity: 5200,
        stature: 3,
      },
      {
        name: 'Viseu Viriatos',
        reference: 'Académico de Viseu',
        city: 'Viseu',
        lat: 40.65,
        lon: -7.91,
        region: 'North-central',
        colours: ['#000000', '#ffffff', '#f2c400'],
        pattern: 'solid',
        stadium: 'Viriathus Park Stadium',
        capacity: 6912,
        stature: 3,
      },
      {
        name: 'Alverca Tagus Blues',
        reference: 'FC Alverca',
        city: 'Alverca do Ribatejo',
        lat: 38.9,
        lon: -9.04,
        region: 'South-central',
        colours: ['#0047ab', '#e30613', '#ffffff'],
        pattern: 'solid',
        stadium: 'Tagus Bank Complex',
        capacity: 6932,
        stature: 3,
      },
    ],
    2: [
      {
        name: 'Tondela Gold-Greens',
        reference: 'Tondela',
        city: 'Tondela',
        lat: 40.52,
        lon: -8.08,
        region: 'North-central',
        colours: ['#ffd700', '#007a3d', '#ffffff'],
        pattern: 'stripes',
        stadium: 'Beira Highlands Ground',
        capacity: 5000,
        stature: 8,
      },
      {
        name: 'Vila das Aves Phoenix',
        reference: 'AFS (AVS Futebol SAD)',
        city: 'Vila das Aves',
        lat: 41.37,
        lon: -8.41,
        region: 'North',
        colours: ['#b0102a', '#000000', '#ffffff'],
        pattern: 'solid',
        stadium: 'Aves Valley Ground',
        capacity: 6230,
        stature: 7,
      },
      {
        name: 'Coimbra Students',
        reference: 'Académica',
        city: 'Coimbra',
        lat: 40.2,
        lon: -8.41,
        region: 'North-central',
        colours: ['#000000', '#ffffff', '#7a7a7a'],
        pattern: 'solid',
        stadium: 'Mondego Students Stadium',
        capacity: 29622,
        stature: 7,
      },
      {
        name: 'Faro Southern Lions',
        reference: 'Farense',
        city: 'Faro',
        lat: 37.02,
        lon: -7.93,
        region: 'South',
        colours: ['#ffffff', '#000000', '#c8a000'],
        pattern: 'solid',
        stadium: 'Algarve Lions Ground',
        capacity: 7000,
        stature: 6,
      },
      {
        name: 'Torres Vedras Garnets',
        reference: 'Torreense',
        city: 'Torres Vedras',
        lat: 39.09,
        lon: -9.26,
        region: 'South-central',
        colours: ['#1e3f8f', '#7b1e2b', '#ffffff'],
        pattern: 'halves',
        stadium: 'Old Towers Ground',
        capacity: 2431,
        stature: 6,
      },
      {
        name: 'Chaves Flavians',
        reference: 'Chaves',
        city: 'Chaves',
        lat: 41.74,
        lon: -7.47,
        region: 'North',
        colours: ['#002f87', '#8b1a2b', '#ffffff'],
        pattern: 'stripes',
        stadium: 'Spa Town Stadium',
        capacity: 8400,
        stature: 6,
      },
      {
        name: 'Portimão Zebras',
        reference: 'Portimonense',
        city: 'Portimão',
        lat: 37.14,
        lon: -8.54,
        region: 'South',
        colours: ['#000000', '#ffffff', '#c8a000'],
        pattern: 'stripes',
        stadium: 'Arade Riverside Stadium',
        capacity: 4961,
        stature: 6,
      },
      {
        name: 'Leiria Unionists',
        reference: 'União de Leiria',
        city: 'Leiria',
        lat: 39.74,
        lon: -8.81,
        region: 'South-central',
        colours: ['#ffffff', '#d71920', '#000000'],
        pattern: 'solid',
        stadium: 'Lis Valley Stadium',
        capacity: 23888,
        stature: 6,
      },
      {
        name: 'Vizela Spa Blues',
        reference: 'Vizela',
        city: 'Vizela',
        lat: 41.38,
        lon: -8.31,
        region: 'North',
        colours: ['#ffffff', '#0047ab', '#000000'],
        pattern: 'solid',
        stadium: 'Vizela River Ground',
        capacity: 6000,
        stature: 6,
      },
      {
        name: 'Matosinhos Seafarers',
        reference: 'Leixões',
        city: 'Matosinhos',
        lat: 41.18,
        lon: -8.69,
        region: 'North',
        colours: ['#e30613', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Harbour Wall Stadium',
        capacity: 6000,
        stature: 5,
      },
      {
        name: 'Feira Fogaceiros',
        reference: 'Feirense',
        city: 'Santa Maria da Feira',
        lat: 40.93,
        lon: -8.54,
        region: 'North-central',
        colours: ['#0047ab', '#ffffff', '#000000'],
        pattern: 'solid',
        stadium: 'Castle Hill Ground',
        capacity: 5401,
        stature: 5,
      },
      {
        name: 'Penafiel Red-Blacks',
        reference: 'Penafiel',
        city: 'Penafiel',
        lat: 41.21,
        lon: -8.29,
        region: 'North',
        colours: ['#e30613', '#000000', '#ffffff'],
        pattern: 'stripes',
        stadium: 'April Freedom Stadium',
        capacity: 5230,
        stature: 4,
      },
      {
        name: 'Felgueiras Reds',
        reference: 'Felgueiras',
        city: 'Felgueiras',
        lat: 41.36,
        lon: -8.2,
        region: 'North',
        colours: ['#d71920', '#ffffff', '#000000'],
        pattern: 'stripes',
        stadium: 'Sousa Valley Stadium',
        capacity: 7540,
        stature: 4,
      },
      {
        name: 'Amarante Bridgemen',
        reference: 'Amarante',
        city: 'Amarante',
        lat: 41.27,
        lon: -8.08,
        region: 'North',
        colours: ['#000000', '#ffffff', '#7a7a7a'],
        pattern: 'stripes',
        stadium: 'Tâmega Bridge Ground',
        capacity: 5000,
        stature: 4,
      },
      {
        name: 'Lourosa Lusitanians',
        reference: 'Lusitânia Lourosa',
        city: 'Lourosa',
        lat: 40.98,
        lon: -8.55,
        region: 'North-central',
        colours: ['#14213d', '#ffffff', '#c8a000'],
        pattern: 'solid',
        stadium: 'Lusitanian Heath Ground',
        capacity: 4900,
        stature: 3,
      },
      {
        name: 'Lisbon Eagles B',
        reference: 'Benfica B',
        city: 'Seixal',
        lat: 38.61,
        lon: -9.11,
        region: 'South-central',
        colours: ['#e30613', '#ffffff', '#1a1a1a'],
        pattern: 'solid',
        stadium: 'Eagles Campus Pitch One',
        capacity: 2644,
        stature: 2,
        reserveOf: 'Lisbon Eagles',
      },
      {
        name: 'Porto Dragons B',
        reference: 'FC Porto B',
        city: 'Vila Nova de Gaia',
        lat: 41.12,
        lon: -8.61,
        region: 'North-central',
        colours: ['#003c8f', '#ffffff', '#f2c400'],
        pattern: 'stripes',
        stadium: 'Gaia Dragon Academy Ground',
        capacity: 3800,
        stature: 2,
        reserveOf: 'Porto Dragons',
      },
      {
        name: 'Lisbon Lions B',
        reference: 'Sporting CP B',
        city: 'Alcochete',
        lat: 38.74,
        lon: -8.96,
        region: 'South-central',
        colours: ['#008057', '#ffffff', '#000000'],
        pattern: 'hoops',
        stadium: 'Lions Academy Arena',
        capacity: 1180,
        stature: 1,
        reserveOf: 'Lisbon Lions',
      },
    ],
  },
  towns: {
    North: [
      { name: 'Viana do Castelo', lat: 41.69, lon: -8.83 },
      { name: 'Póvoa de Varzim', lat: 41.38, lon: -8.76 },
      { name: 'Esposende', lat: 41.53, lon: -8.78 },
      { name: 'Fafe', lat: 41.45, lon: -8.17 },
      { name: 'Vieira do Minho', lat: 41.63, lon: -8.14 },
      { name: 'Ponte de Lima', lat: 41.77, lon: -8.58 },
      { name: 'Valença', lat: 42.03, lon: -8.63 },
      { name: 'Monção', lat: 42.08, lon: -8.48 },
      { name: 'Arcos de Valdevez', lat: 41.85, lon: -8.42 },
      { name: 'Caminha', lat: 41.87, lon: -8.84 },
      { name: 'Vila Verde', lat: 41.65, lon: -8.43 },
      { name: 'Amares', lat: 41.63, lon: -8.35 },
      { name: 'Póvoa de Lanhoso', lat: 41.58, lon: -8.27 },
      { name: 'Cabeceiras de Basto', lat: 41.51, lon: -7.99 },
      { name: 'Celorico de Basto', lat: 41.39, lon: -8.0 },
      { name: 'Mondim de Basto', lat: 41.41, lon: -7.95 },
      { name: 'Vila Real', lat: 41.3, lon: -7.74 },
      { name: 'Bragança', lat: 41.81, lon: -6.76 },
      { name: 'Mirandela', lat: 41.49, lon: -7.18 },
      { name: 'Macedo de Cavaleiros', lat: 41.54, lon: -6.96 },
      { name: 'Valpaços', lat: 41.61, lon: -7.31 },
      { name: 'Montalegre', lat: 41.82, lon: -7.79 },
      { name: 'Vila Pouca de Aguiar', lat: 41.5, lon: -7.64 },
      { name: 'Peso da Régua', lat: 41.16, lon: -7.79 },
      { name: 'Santo Tirso', lat: 41.34, lon: -8.48 },
      { name: 'Trofa', lat: 41.34, lon: -8.56 },
      { name: 'Maia', lat: 41.24, lon: -8.62 },
      { name: 'Valongo', lat: 41.19, lon: -8.5 },
      { name: 'Lousada', lat: 41.28, lon: -8.28 },
      { name: 'Paços de Ferreira', lat: 41.28, lon: -8.38 },
      { name: 'Paredes', lat: 41.21, lon: -8.33 },
      { name: 'Marco de Canaveses', lat: 41.18, lon: -8.15 },
      { name: 'Riba de Ave', lat: 41.4, lon: -8.38 },
      { name: 'Caldas das Taipas', lat: 41.48, lon: -8.35 },
    ],
    'North-central': [
      { name: 'Espinho', lat: 41.01, lon: -8.64 },
      { name: 'Gondomar', lat: 41.14, lon: -8.53 },
      { name: 'Oliveira de Azeméis', lat: 40.84, lon: -8.48 },
      { name: 'São João da Madeira', lat: 40.9, lon: -8.49 },
      { name: 'Ovar', lat: 40.86, lon: -8.63 },
      { name: 'Estarreja', lat: 40.75, lon: -8.57 },
      { name: 'Vale de Cambra', lat: 40.85, lon: -8.39 },
      { name: 'Aveiro', lat: 40.64, lon: -8.65 },
      { name: 'Ílhavo', lat: 40.6, lon: -8.67 },
      { name: 'Vagos', lat: 40.56, lon: -8.68 },
      { name: 'Águeda', lat: 40.57, lon: -8.45 },
      { name: 'Oliveira do Bairro', lat: 40.51, lon: -8.49 },
      { name: 'Anadia', lat: 40.44, lon: -8.43 },
      { name: 'Mealhada', lat: 40.38, lon: -8.45 },
      { name: 'Sever do Vouga', lat: 40.73, lon: -8.37 },
      { name: 'Oliveira de Frades', lat: 40.73, lon: -8.18 },
      { name: 'São Pedro do Sul', lat: 40.76, lon: -8.06 },
      { name: 'Castro Daire', lat: 40.9, lon: -7.93 },
      { name: 'Lamego', lat: 41.1, lon: -7.81 },
      { name: 'Sátão', lat: 40.74, lon: -7.73 },
      { name: 'Mangualde', lat: 40.6, lon: -7.76 },
      { name: 'Nelas', lat: 40.53, lon: -7.85 },
      { name: 'Carregal do Sal', lat: 40.43, lon: -7.99 },
      { name: 'Mortágua', lat: 40.4, lon: -8.23 },
      { name: 'Seia', lat: 40.42, lon: -7.7 },
      { name: 'Gouveia', lat: 40.49, lon: -7.59 },
      { name: 'Guarda', lat: 40.54, lon: -7.27 },
      { name: 'Oliveira do Hospital', lat: 40.36, lon: -7.86 },
      { name: 'Tábua', lat: 40.36, lon: -8.03 },
      { name: 'Arganil', lat: 40.22, lon: -8.05 },
      { name: 'Cantanhede', lat: 40.35, lon: -8.59 },
      { name: 'Figueira da Foz', lat: 40.15, lon: -8.86 },
      { name: 'Montemor-o-Velho', lat: 40.17, lon: -8.68 },
      { name: 'Condeixa-a-Nova', lat: 40.11, lon: -8.5 },
      { name: 'Lousã', lat: 40.11, lon: -8.25 },
      { name: 'Penacova', lat: 40.27, lon: -8.28 },
    ],
    'South-central': [
      { name: 'Marinha Grande', lat: 39.75, lon: -8.93 },
      { name: 'Pombal', lat: 39.92, lon: -8.63 },
      { name: 'Batalha', lat: 39.66, lon: -8.82 },
      { name: 'Porto de Mós', lat: 39.6, lon: -8.82 },
      { name: 'Fátima', lat: 39.63, lon: -8.67 },
      { name: 'Ourém', lat: 39.66, lon: -8.58 },
      { name: 'Alcobaça', lat: 39.55, lon: -8.98 },
      { name: 'Nazaré', lat: 39.6, lon: -9.07 },
      { name: 'Caldas da Rainha', lat: 39.4, lon: -9.14 },
      { name: 'Peniche', lat: 39.36, lon: -9.38 },
      { name: 'Lourinhã', lat: 39.24, lon: -9.31 },
      { name: 'Rio Maior', lat: 39.34, lon: -8.94 },
      { name: 'Santarém', lat: 39.24, lon: -8.69 },
      { name: 'Almeirim', lat: 39.21, lon: -8.63 },
      { name: 'Cartaxo', lat: 39.16, lon: -8.79 },
      { name: 'Torres Novas', lat: 39.48, lon: -8.54 },
      { name: 'Entroncamento', lat: 39.46, lon: -8.47 },
      { name: 'Tomar', lat: 39.6, lon: -8.41 },
      { name: 'Abrantes', lat: 39.46, lon: -8.2 },
      { name: 'Coruche', lat: 38.96, lon: -8.53 },
      { name: 'Benavente', lat: 38.98, lon: -8.81 },
      { name: 'Vila Franca de Xira', lat: 38.95, lon: -8.99 },
      { name: 'Mafra', lat: 38.94, lon: -9.33 },
      { name: 'Sintra', lat: 38.8, lon: -9.38 },
      { name: 'Loures', lat: 38.83, lon: -9.17 },
      { name: 'Sacavém', lat: 38.79, lon: -9.1 },
      { name: 'Odivelas', lat: 38.79, lon: -9.18 },
      { name: 'Oeiras', lat: 38.69, lon: -9.31 },
      { name: 'Almada', lat: 38.68, lon: -9.16 },
      { name: 'Barreiro', lat: 38.66, lon: -9.07 },
      { name: 'Moita', lat: 38.65, lon: -9.0 },
      { name: 'Montijo', lat: 38.71, lon: -8.97 },
      { name: 'Sertã', lat: 39.8, lon: -8.1 },
      { name: 'Castelo Branco', lat: 39.82, lon: -7.49 },
      { name: 'Fundão', lat: 40.14, lon: -7.5 },
      { name: 'Covilhã', lat: 40.28, lon: -7.5 },
    ],
    South: [
      { name: 'Setúbal', lat: 38.52, lon: -8.89 },
      { name: 'Palmela', lat: 38.57, lon: -8.9 },
      { name: 'Sesimbra', lat: 38.44, lon: -9.1 },
      { name: 'Alcácer do Sal', lat: 38.37, lon: -8.51 },
      { name: 'Grândola', lat: 38.18, lon: -8.57 },
      { name: 'Santiago do Cacém', lat: 38.02, lon: -8.69 },
      { name: 'Sines', lat: 37.96, lon: -8.87 },
      { name: 'Vendas Novas', lat: 38.68, lon: -8.46 },
      { name: 'Montemor-o-Novo', lat: 38.65, lon: -8.22 },
      { name: 'Évora', lat: 38.57, lon: -7.91 },
      { name: 'Estremoz', lat: 38.84, lon: -7.59 },
      { name: 'Elvas', lat: 38.88, lon: -7.16 },
      { name: 'Portalegre', lat: 39.29, lon: -7.43 },
      { name: 'Ponte de Sor', lat: 39.25, lon: -8.01 },
      { name: 'Beja', lat: 38.02, lon: -7.86 },
      { name: 'Moura', lat: 38.14, lon: -7.45 },
      { name: 'Serpa', lat: 37.94, lon: -7.6 },
      { name: 'Castro Verde', lat: 37.7, lon: -8.09 },
      { name: 'Lagos', lat: 37.1, lon: -8.67 },
      { name: 'Lagoa', lat: 37.13, lon: -8.45 },
      { name: 'Silves', lat: 37.19, lon: -8.44 },
      { name: 'Albufeira', lat: 37.09, lon: -8.25 },
      { name: 'Quarteira', lat: 37.07, lon: -8.1 },
      { name: 'Loulé', lat: 37.14, lon: -8.02 },
      { name: 'Olhão', lat: 37.03, lon: -7.84 },
      { name: 'Tavira', lat: 37.13, lon: -7.65 },
      { name: 'Vila Real de Santo António', lat: 37.19, lon: -7.42 },
      { name: 'Machico', lat: 32.72, lon: -16.77 },
      { name: 'Santa Cruz', lat: 32.69, lon: -16.79 },
      { name: 'Câmara de Lobos', lat: 32.65, lon: -16.98 },
      { name: 'Ribeira Brava', lat: 32.67, lon: -17.06 },
      { name: 'Ribeira Grande', lat: 37.82, lon: -25.52 },
      { name: 'Vila Franca do Campo', lat: 37.72, lon: -25.43 },
      { name: 'Angra do Heroísmo', lat: 38.65, lon: -27.22 },
      { name: 'Praia da Vitória', lat: 38.73, lon: -27.07 },
      { name: 'Horta', lat: 38.53, lon: -28.63 },
    ],
  },
  groupRegions: {
    3: [
      ['North', 'North-central'],
      ['South-central', 'South'],
    ],
    4: [['North'], ['North-central'], ['South-central'], ['South']],
  },
};
