export const ENGINE_VERSION = 'match-3';
export const CONFIG = {
  match: {
    ratingBase: 6.5,
    goalsPerMatch: 2.7,
    homeAdvantage: 0.18,
    reputationSlope: 0.026,
    minimumMoments: 6,
    maximumMoments: 15,
    fatiguePerMinute: 0.48,
    substitutionFatigue: 82,
    minimumSubstitutionMinute: 65,
    attributeScale: 0.004,
    defenderScale: 0.0025,
    fatigueScale: 0.002,
    traitBonus: 0.08,
    baseDecisionProbability: 0.62,
    shotConversion: 0.12,
    defensiveFailureConversion: 0.16,
    personalGoalShare: 0.35,
    passPerMinute: 0.48,
    decisionRatingGain: 0.12,
    decisionRatingLoss: 0.13,
    scoringRatingBonus: 0.55,
    xp: {
      perMinute: 1.2,
      ratingThreshold: 6,
      perRating: 25,
      perGoal: 30,
      perAssist: 20,
      perObjective: 15,
    },
    fame: { ratingThreshold: 6.5, perRating: 2, perGoal: 2 },
  },
  gallery: { clubs: 15, players: 8, ages: [17, 28, 42] as const },
  workers: { transportBatchEntries: 32, transportYieldMs: 8 },
  saves: {
    schemaVersion: 5,
    slotCount: 3,
    maxFileBytes: 128 * 1024 * 1024,
    autosaveDelayMs: 450,
    leaseDurationMs: 30000,
    heartbeatMs: 5000,
  },
  accessibility: { minFontScale: 0.85, maxFontScale: 1.3 },
  world: {
    nationalWeeksPerSeason: 60,
    nationalCupWeeks: [5, 11, 17, 23, 29, 35, 41, 47, 53] as const,
    countries: 6,
    tiers: 4,
    clubsPerLeague: 8,
    squadSize: 22,
    startSeason: 2026,
    weeksPerSeason: 34,
    leagueRounds: 28,
    cupWeeks: [4, 10, 16, 22, 30] as const,
    movementPlaces: 2,
    baseGoals: 1.35,
    homeAdvantage: 0.14,
    strengthScale: 0.012,
    maxGoals: 10,
    developmentChance: 0.045,
    declineChance: 0.035,
    transferWeeks: [8, 18, 31] as const,
    managerWeeks: [12, 24] as const,
    intakeWeek: 31,
    retirementAge: 38,
    forcedRetirementAge: 43,
    youthIntakePerClub: 2,
    generation: {
      reputationCeiling: 99,
      reputationFloor: 87,
      reputationTierStep: 15,
      managerAge: [35, 68],
      managerAbility: [25, 95],
      personality: [15, 95],
      adultAge: [17, 36],
      veteranAge: [38, 42],
      youthAge: [16, 18],
      attributeReputationWeight: 0.7,
      attributeBase: [5, 19],
      youngAge: 20,
      youngPenalty: 12,
      attributeSpread: 14,
      positionalBonus: 8,
      keeperFinishing: [1, 20],
      keeperSpread: [-10, 15],
      outfieldKeeping: [1, 25],
      potentialBonus: [8, 18],
      youngPotentialAge: 22,
      youngPotentialBonus: 30,
      secondaryFamiliarity: [35, 85],
      morale: [55, 85],
      form: [45, 75],
      contractYears: [1, 4],
      wageFloor: 50,
      wageBase: 0.12,
      wageReputationDivisor: 1000,
      appearanceBonus: 0.1,
      goalBonus: 0.15,
      cleanSheetBonus: 0.12,
      releaseWageMultiplier: 250,
      sellOnPercent: [0, 15],
      loyaltyWageMultiplier: 4,
      stadiumCapacityFactor: [8, 20],
      stadiumReputationDivisor: 4,
      pitchQuality: [45, 95],
      balanceFactor: 200,
      incomeFactor: 12,
      costsFactor: 3,
      transferFactor: 60,
      wageBudgetFactor: 8,
      cultureRange: [20, 95],
      fanOwnedChance: 0.25,
      roomMood: 65,
    },
    background: {
      reputationWeight: 0.6,
      squadWeight: 0.4,
      minimumGoals: 0.15,
      penaltyWinnerChance: 0.5,
      penaltyLoserGoals: [2, 5],
      assistedGoalChance: 0.78,
      scorerWeights: { GK: 0.01, ST: 5, winger: 3, midfield: 1.5, defender: 0.5 },
      ratingBase: 6.1,
      ratingWin: 0.6,
      ratingLoss: -0.4,
      ratingGoal: 0.8,
      ratingVariation: 0.8,
      minimumRating: 3,
      maximumRating: 10,
      formRetention: 0.85,
      formRatingWeight: 0.15,
      moraleResultDelta: 2,
      matchFatigue: 12,
      weeklyRecovery: 10,
      fitnessFatigueWeight: 0.2,
      managerPointsThreshold: 0.9,
      managerDismissalChance: 0.8,
      transferContractYears: 2,
      transferBudgetBalanceShare: 0.35,
    },
    development: {
      youthAge: 24,
      growthEndAge: 29,
      youthFactor: 1.7,
      adultFactor: 0.65,
      mentalEndAge: 36,
      mentalFactor: 0.65,
      professionalismBase: 0.6,
      declineStartAge: 30,
      declineAgeDivisor: 5,
      physicalDeclineFactor: 2,
      mentalDeclineFactor: 0.15,
      technicalDeclineFactor: 0.7,
      keeperGrowthEndAge: 32,
      keeperDeclineAge: 35,
      keeperDeclineDivisor: 4,
      retirementChance: 0.65,
    },
  },
} as const;
